import { ARLCompany, ClientCompany, LeadProspect, PilaRecord, FieldVisit, MedicalRecord, RUIIntermediaryProfile, WhatsAppMessage, UserProfile, AgencyProfile } from '@/types';

export const INITIAL_ARLS: ARLCompany[] = [
  {
    id: 'positiva',
    name: 'Positiva Compañía de Seguros S.A.',
    shortName: 'Positiva ARL',
    superintendenciaCode: '14-23',
    phone: '018000 111 170',
    website: 'https://www.positiva.gov.co',
    colorTheme: '#D97706',
    logo: '🛡️',
    status: 'ACTIVA',
    commissionRegime: 'GASTOS_ADMINISTRACION',
    notes: 'ARL estatal con amplia cobertura en sector público, educación y agroindustria.',
    defaultCommissionMatrix: {
      EMPRESA_NUEVA: { CLASE_I: 7.5, CLASE_II: 8.0, CLASE_III: 8.5, CLASE_IV: 8.5, CLASE_V: 8.5 },
      NOMBRAMIENTO: { CLASE_I: 5.5, CLASE_II: 6.0, CLASE_III: 6.5, CLASE_IV: 7.0, CLASE_V: 7.5 },
      CAMBIO_INTERMEDIARIO: { CLASE_I: 6.5, CLASE_II: 7.0, CLASE_III: 7.5, CLASE_IV: 8.0, CLASE_V: 8.0 },
    },
    economicActivityCommissions: [
      { id: 'pos-act-1', riskClass: 'CLASE_V', ciiuCode: '4111', activityName: 'Construcción de edificios residenciales', commissionRate: 8.5, notes: 'Tarifa preferencial para agremiaciones constructoras' },
      { id: 'pos-act-2', riskClass: 'CLASE_V', ciiuCode: '0510', activityName: 'Extracción de hulla (carbón de piedra)', commissionRate: 9.0, notes: 'Minería subterránea bajo convenio de supervisión' },
      { id: 'pos-act-3', riskClass: 'CLASE_IV', ciiuCode: '4923', activityName: 'Transporte de carga por carretera', commissionRate: 8.5, notes: 'Flotas de carga pesada' },
      { id: 'pos-act-4', riskClass: 'CLASE_III', ciiuCode: '1011', activityName: 'Procesamiento y conservación de carne', commissionRate: 8.5, notes: 'Sector agroindustrial' },
      { id: 'pos-act-5', riskClass: 'CLASE_I', ciiuCode: '8411', activityName: 'Actividades de la administración pública en general', commissionRate: 8.0, notes: 'Entidades gubernamentales' },
    ],
  },
  {
    id: 'sura',
    name: 'Seguros de Vida Suramericana S.A. (ARL SURA)',
    shortName: 'ARL SURA',
    superintendenciaCode: '14-18',
    phone: '018000 511 414',
    website: 'https://www.segurossura.com.co',
    colorTheme: '#0033A0',
    logo: '🐯',
    status: 'ACTIVA',
    commissionRegime: 'GASTOS_ADMINISTRACION',
    notes: 'Líder en prevención técnica y reconocimiento puntual de intermediación (Ley 1562/2012).',
    defaultCommissionMatrix: {
      EMPRESA_NUEVA: { CLASE_I: 8.0, CLASE_II: 8.5, CLASE_III: 9.0, CLASE_IV: 9.0, CLASE_V: 9.0 },
      NOMBRAMIENTO: { CLASE_I: 6.0, CLASE_II: 6.5, CLASE_III: 7.0, CLASE_IV: 7.5, CLASE_V: 8.0 },
      CAMBIO_INTERMEDIARIO: { CLASE_I: 7.0, CLASE_II: 7.5, CLASE_III: 8.0, CLASE_IV: 8.5, CLASE_V: 9.0 },
    },
    economicActivityCommissions: [
      { id: 'sur-act-1', riskClass: 'CLASE_V', ciiuCode: '4111', activityName: 'Construcción de edificios residenciales y obras civiles', commissionRate: 9.5, notes: 'Tasa especial para constructoras AAA con PVE osteomuscular' },
      { id: 'sur-act-2', riskClass: 'CLASE_V', ciiuCode: '0610', activityName: 'Extracción de petróleo crudo y gas natural', commissionRate: 9.0, notes: 'Operaciones de exploración y campo' },
      { id: 'sur-act-3', riskClass: 'CLASE_IV', ciiuCode: '4923', activityName: 'Transporte de carga por carretera nacional e internacional', commissionRate: 9.0, notes: 'Convenio logístico empresarial' },
      { id: 'sur-act-4', riskClass: 'CLASE_III', ciiuCode: '1081', activityName: 'Elaboración de productos alimenticios y bebidas', commissionRate: 8.5, notes: 'Industria procesadora de alimentos' },
      { id: 'sur-act-5', riskClass: 'CLASE_II', ciiuCode: '1410', activityName: 'Confección de prendas de vestir', commissionRate: 8.5, notes: 'Sector textil maquilador' },
      { id: 'sur-act-6', riskClass: 'CLASE_I', ciiuCode: '6412', activityName: 'Bancos comerciales y actividades financieras', commissionRate: 8.0, notes: 'Sector corporativo financiero' },
    ],
  },
  {
    id: 'bolivar',
    name: 'Seguros Bolívar S.A.',
    shortName: 'ARL Bolívar',
    superintendenciaCode: '14-25',
    phone: '018000 123 322',
    website: 'https://www.segurosbolivar.com',
    colorTheme: '#059669',
    logo: '🟢',
    status: 'ACTIVA',
    commissionRegime: 'GASTOS_ADMINISTRACION',
    notes: 'Especialista en constructoras, transporte e industria manufacturera.',
    defaultCommissionMatrix: {
      EMPRESA_NUEVA: { CLASE_I: 8.0, CLASE_II: 8.5, CLASE_III: 9.0, CLASE_IV: 9.0, CLASE_V: 9.0 },
      NOMBRAMIENTO: { CLASE_I: 5.5, CLASE_II: 6.0, CLASE_III: 6.5, CLASE_IV: 7.0, CLASE_V: 7.5 },
      CAMBIO_INTERMEDIARIO: { CLASE_I: 7.0, CLASE_II: 7.5, CLASE_III: 8.0, CLASE_IV: 8.5, CLASE_V: 8.5 },
    },
    economicActivityCommissions: [
      { id: 'bol-act-1', riskClass: 'CLASE_V', ciiuCode: '4290', activityName: 'Construcción de otras obras de ingeniería civil', commissionRate: 9.2, notes: 'Infraestructura vial y puentes' },
      { id: 'bol-act-2', riskClass: 'CLASE_IV', ciiuCode: '4921', activityName: 'Transporte urbano y metropolitano de pasajeros', commissionRate: 8.8, notes: 'Operadores de transporte masivo' },
      { id: 'bol-act-3', riskClass: 'CLASE_III', ciiuCode: '2011', activityName: 'Fabricación de sustancias químicas básicas', commissionRate: 8.5, notes: 'Química industrial' },
    ],
  },
  {
    id: 'colpatria',
    name: 'AXA Colpatria Seguros de Vida S.A.',
    shortName: 'AXA Colpatria',
    superintendenciaCode: '14-04',
    phone: '018000 512 620',
    website: 'https://www.axacolpatria.co',
    colorTheme: '#DC2626',
    logo: '🔷',
    status: 'ACTIVA',
    commissionRegime: 'GASTOS_ADMINISTRACION',
    notes: 'Fuerte en sector servicios, finanzas, hidrocarburos y comercio masivo.',
    defaultCommissionMatrix: {
      EMPRESA_NUEVA: { CLASE_I: 8.0, CLASE_II: 8.5, CLASE_III: 9.0, CLASE_IV: 9.0, CLASE_V: 9.0 },
      NOMBRAMIENTO: { CLASE_I: 6.0, CLASE_II: 6.5, CLASE_III: 7.2, CLASE_IV: 7.5, CLASE_V: 8.0 },
      CAMBIO_INTERMEDIARIO: { CLASE_I: 7.0, CLASE_II: 7.5, CLASE_III: 8.0, CLASE_IV: 8.5, CLASE_V: 9.0 },
    },
    economicActivityCommissions: [
      { id: 'colp-act-1', riskClass: 'CLASE_V', ciiuCode: '4390', activityName: 'Otras actividades especializadas de construcción', commissionRate: 9.0, notes: 'Acabados y obras menores' },
      { id: 'colp-act-2', riskClass: 'CLASE_IV', ciiuCode: '5229', activityName: 'Otras actividades de apoyo al transporte', commissionRate: 8.5, notes: 'Operadores portuarios y aduaneros' },
      { id: 'colp-act-3', riskClass: 'CLASE_I', ciiuCode: '6511', activityName: 'Seguros de vida y reaseguros', commissionRate: 8.0, notes: 'Finanzas' },
    ],
  },
  {
    id: 'colmena',
    name: 'Colmena Seguros (Colmena Riesgos Laborales)',
    shortName: 'Colmena ARL',
    superintendenciaCode: '14-28',
    phone: '018000 919 667',
    website: 'https://www.colmenaseguros.com',
    colorTheme: '#D97706',
    logo: '🐝',
    status: 'ACTIVA',
    commissionRegime: 'GASTOS_ADMINISTRACION',
    notes: 'Pionera en ergonomía, pymes y asesoría en medicina laboral.',
    defaultCommissionMatrix: {
      EMPRESA_NUEVA: { CLASE_I: 7.5, CLASE_II: 8.0, CLASE_III: 8.5, CLASE_IV: 9.0, CLASE_V: 9.0 },
      NOMBRAMIENTO: { CLASE_I: 5.5, CLASE_II: 6.0, CLASE_III: 6.5, CLASE_IV: 7.0, CLASE_V: 7.5 },
      CAMBIO_INTERMEDIARIO: { CLASE_I: 6.5, CLASE_II: 7.0, CLASE_III: 7.5, CLASE_IV: 8.0, CLASE_V: 8.5 },
    },
    economicActivityCommissions: [
      { id: 'colm-act-1', riskClass: 'CLASE_V', ciiuCode: '4112', activityName: 'Construcción de edificios no residenciales', commissionRate: 9.0, notes: 'Bodegas y centros comerciales' },
      { id: 'colm-act-2', riskClass: 'CLASE_III', ciiuCode: '2511', activityName: 'Fabricación de productos metálicos para uso estructural', commissionRate: 8.5, notes: 'Estructuras metálicas' },
    ],
  },
];

export const INITIAL_CLIENTS: ClientCompany[] = [
  {
    id: 'cli-001',
    nit: '900.452.128-4',
    name: 'Constructora Andina del Caribe S.A.S.',
    economicActivity: 'Construcción de edificios residenciales y obras civiles',
    ciiuCode: '4111',
    primaryArlId: 'sura',
    riskClass: 'CLASE_V',
    monthlyIbc: 185000000,
    employeeCount: 94,
    address: 'Av. Circunvalar No. 84-12',
    city: 'Barranquilla',
    conceptType: 'EMPRESA_NUEVA',
    status: 'ACTIVO',
    workCenters: [
      {
        id: 'wc-001-1',
        name: 'Sede Administrativa Principal (Oficinas)',
        ciiuCode: '8211',
        riskClass: 'CLASE_I',
        employeeCount: 14,
        monthlyIbc: 35000000,
        city: 'Barranquilla'
      },
      {
        id: 'wc-001-2',
        name: 'Planta de Mezclas, Talleres & Logística',
        ciiuCode: '2395',
        riskClass: 'CLASE_III',
        employeeCount: 20,
        monthlyIbc: 40000000,
        city: 'Soledad'
      },
      {
        id: 'wc-001-3',
        name: 'Frentes de Obra y Alturas (Torre Mar & Vías)',
        ciiuCode: '4111',
        riskClass: 'CLASE_V',
        employeeCount: 60,
        monthlyIbc: 110000000,
        city: 'Barranquilla'
      }
    ],
    
    // Representante Legal
    legalRepName: 'Ing. Carlos Mendoza Rincón',
    legalRepEmail: 'carlos.mendoza@constructoraandina.com',
    legalRepPhone: '+57 310 445 8899',

    // Responsable SST
    sstResponsibleName: 'Especialista Laura Marcela Osorio',
    sstResponsibleEmail: 'sst@constructoraandina.com',
    sstResponsiblePhone: '+57 301 223 9988',
    sstResponsibleLicense: 'Lic. SST Res. 9841-2022',

    lastPilaDate: '2026-08-08',
    returnPercentage: 30,
    standardsCount: 60,
    standardsScore: 73,
    standardsRating: 'MODERADAMENTE_ACEPTABLE',
    lastStandardsAuditDate: '2026-08-15',
    createdAt: '2025-11-10',
  },
  {
    id: 'cli-002',
    nit: '860.012.345-1',
    name: 'Industrias Químicas del Valle S.A.',
    economicActivity: 'Fabricación de sustancias químicas y fertilizantes',
    ciiuCode: '2011',
    primaryArlId: 'bolivar',
    riskClass: 'CLASE_III',
    monthlyIbc: 320000000,
    employeeCount: 145,
    address: 'Zona Industrial Yumbo Km 4',
    city: 'Cali',
    conceptType: 'NOMBRAMIENTO',
    status: 'ACTIVO',
    workCenters: [
      {
        id: 'wc-002-1',
        name: 'Oficinas Administrativas & Ventas',
        ciiuCode: '8211',
        riskClass: 'CLASE_I',
        employeeCount: 25,
        monthlyIbc: 70000000,
        city: 'Cali'
      },
      {
        id: 'wc-002-2',
        name: 'Planta de Síntesis Química & Reactores',
        ciiuCode: '2011',
        riskClass: 'CLASE_III',
        employeeCount: 90,
        monthlyIbc: 190000000,
        city: 'Yumbo'
      },
      {
        id: 'wc-002-3',
        name: 'Centro de Almacenamiento de Solventes e Inflamables',
        ciiuCode: '5210',
        riskClass: 'CLASE_IV',
        employeeCount: 30,
        monthlyIbc: 60000000,
        city: 'Yumbo'
      }
    ],

    // Representante Legal
    legalRepName: 'Dra. Beatriz Helena Restrepo',
    legalRepEmail: 'gerencia@iquimicas.com',
    legalRepPhone: '+57 315 889 0012',

    // Responsable SST
    sstResponsibleName: 'Ing. Mauricio Gómez Quintero',
    sstResponsibleEmail: 'seguridad@iquimicas.com',
    sstResponsiblePhone: '+57 317 400 5511',
    sstResponsibleLicense: 'Lic. SST Res. 1204-2021',

    lastPilaDate: '2026-08-05',
    returnPercentage: 25,
    standardsCount: 60,
    standardsScore: 88,
    standardsRating: 'ACEPTABLE',
    lastStandardsAuditDate: '2026-08-20',
    createdAt: '2026-01-15',
  },
  {
    id: 'cli-003',
    nit: '901.124.580-9',
    name: 'Logística & Transportes del Norte S.A.S.',
    economicActivity: 'Transporte de carga por carretera y distribución',
    ciiuCode: '4923',
    primaryArlId: 'colpatria',
    riskClass: 'CLASE_IV',
    monthlyIbc: 142000000,
    employeeCount: 68,
    address: 'Calle 100 No. 15-32 Piso 4',
    city: 'Medellín',
    conceptType: 'CAMBIO_INTERMEDIARIO',
    status: 'ACTIVO',
    returnPercentage: 20,

    // Representante Legal
    legalRepName: 'Felipe Correa Giraldo',
    legalRepEmail: 'fcorrea@logisticanorte.com',
    legalRepPhone: '+57 300 765 4321',

    // Responsable SST
    sstResponsibleName: 'Tecnóloga Andrea Villa',
    sstResponsibleEmail: 'sst@logisticanorte.com',
    sstResponsiblePhone: '+57 320 611 2233',
    sstResponsibleLicense: 'Lic. SST Res. 4501-2023',

    lastPilaDate: '2026-08-09',
    standardsCount: 60,
    standardsScore: 64,
    standardsRating: 'MODERADAMENTE_ACEPTABLE',
    lastStandardsAuditDate: '2026-08-01',
    createdAt: '2026-02-20',
  },
  {
    id: 'cli-004',
    nit: '800.991.023-3',
    name: 'Financiera & Consultores Alianza S.A.',
    economicActivity: 'Actividades de servicios financieros y asesoría contable',
    ciiuCode: '6499',
    primaryArlId: 'positiva',
    riskClass: 'CLASE_I',
    monthlyIbc: 98000000,
    employeeCount: 32,
    address: 'Carrera 7 No. 72-10 Torre B',
    city: 'Bogotá',
    conceptType: 'EMPRESA_NUEVA',
    status: 'ACTIVO',
    returnPercentage: 15,

    // Representante Legal
    legalRepName: 'Dra. Patricia Salamanca',
    legalRepEmail: 'psalamanca@alianzafin.co',
    legalRepPhone: '+57 311 900 1122',

    // Responsable SST
    sstResponsibleName: 'Dra. Claudia Ortiz',
    sstResponsibleEmail: 'cortiz@alianzafin.co',
    sstResponsiblePhone: '+57 304 555 6677',
    sstResponsibleLicense: 'Lic. SST Res. 3310-2020',

    lastPilaDate: '2026-08-04',
    standardsCount: 21,
    standardsScore: 92,
    standardsRating: 'ACEPTABLE',
    lastStandardsAuditDate: '2026-06-18',
    createdAt: '2026-03-01',
  },
  {
    id: 'cli-005',
    nit: '900.887.412-0',
    name: 'Textiles & Confecciones Bucaramanga Ltda.',
    economicActivity: 'Fabricación de prendas de vestir y textiles',
    ciiuCode: '1410',
    primaryArlId: 'colmena',
    riskClass: 'CLASE_II',
    monthlyIbc: 76000000,
    employeeCount: 45,
    address: 'Calle 36 No. 18-24',
    city: 'Bucaramanga',
    conceptType: 'NOMBRAMIENTO',
    status: 'MORA',
    returnPercentage: 20,

    // Representante Legal
    legalRepName: 'Gustavo Plata Serrano',
    legalRepEmail: 'gplata@textilesbga.com.co',
    legalRepPhone: '+57 318 432 1098',

    // Responsable SST
    sstResponsibleName: 'Ing. Diego Rueda',
    sstResponsibleEmail: 'sst@textilesbga.com.co',
    sstResponsiblePhone: '+57 314 220 8899',
    sstResponsibleLicense: 'Lic. SST Res. 7741-2022',

    lastPilaDate: '2026-06-10',
    standardsCount: 21,
    standardsScore: 52,
    standardsRating: 'CRITICO',
    lastStandardsAuditDate: '2026-05-10',
    createdAt: '2025-03-12',
  },
];

export const INITIAL_LEADS: LeadProspect[] = [
  {
    id: 'lead-001',
    name: 'Distribuciones Avícolas del Oriente S.A.S.',
    nit: '901.445.670-1',
    economicActivity: 'Cría, beneficio y procesamiento de aves de corral',
    ciiuCode: '0145',
    currentArlId: 'positiva',
    proposedArlId: 'sura',
    riskClass: 'CLASE_IV',
    estimatedIbc: 210000000,
    employeeCount: 88,
    city: 'Bucaramanga',
    stage: 'CARTA_NOMBRAMIENTO',
    source: 'REFERIDO',
    conceptType: 'CAMBIO_INTERMEDIARIO',
    workCenters: [
      {
        id: 'wc-lead-1-1',
        name: 'Sede Administrativa & Comercial',
        riskClass: 'CLASE_I',
        employeeCount: 18,
        monthlyIbc: 45000000,
        city: 'Bucaramanga'
      },
      {
        id: 'wc-lead-1-2',
        name: 'Granjas Avícolas & Incubación',
        riskClass: 'CLASE_III',
        employeeCount: 30,
        monthlyIbc: 65000000,
        city: 'Lebrija'
      },
      {
        id: 'wc-lead-1-3',
        name: 'Planta de Beneficio, Desprese y Frigoríficos',
        riskClass: 'CLASE_IV',
        employeeCount: 40,
        monthlyIbc: 100000000,
        city: 'Girón'
      }
    ],

    // Representante Legal
    legalRepName: 'Dr. Hernán Barajas Gómez',
    legalRepEmail: 'hbarajas@avicoriente.com',
    legalRepPhone: '+57 316 778 9900',

    // Responsable SST
    sstResponsibleName: 'Ing. Sandra Milena Peña',
    sstResponsibleEmail: 'sst@avicoriente.com',
    sstResponsiblePhone: '+57 312 334 5566',

    nextFollowUpDate: '2026-09-02',
    nextFollowUpAction: 'Radicar carta de traslado ante ARL SURA con copia a Positiva.',
    estimatedMonthlyCommission: 720000,
    notes: 'Inconformes con tiempos de respuesta técnica de Positiva. Quieren pasarse a SURA.',
    createdAt: '2026-07-20',
  },
  {
    id: 'lead-002',
    name: 'Agroindustrias del Sinú Ltda.',
    nit: '812.003.456-7',
    economicActivity: 'Cultivo de palma africana y extracción de aceites',
    ciiuCode: '0126',
    currentArlId: 'bolivar',
    proposedArlId: 'bolivar',
    riskClass: 'CLASE_III',
    estimatedIbc: 165000000,
    employeeCount: 72,
    city: 'Montería',
    stage: 'PROPUESTA_ENVIADA',
    source: 'WHATSAPP',
    conceptType: 'NOMBRAMIENTO',
    workCenters: [
      {
        id: 'wc-lead-2-1',
        name: 'Oficina Central Administrativa',
        riskClass: 'CLASE_I',
        employeeCount: 12,
        monthlyIbc: 30000000,
        city: 'Montería'
      },
      {
        id: 'wc-lead-2-2',
        name: 'Plantaciones & Extracción en Campo',
        riskClass: 'CLASE_III',
        employeeCount: 60,
        monthlyIbc: 135000000,
        city: 'Cereté'
      }
    ],

    // Representante Legal
    legalRepName: 'Álvaro José Hoyos',
    legalRepEmail: 'ahoyos@agrosinu.com.co',
    legalRepPhone: '+57 310 987 6543',

    // Responsable SST
    sstResponsibleName: 'Tec. Jorge Martínez',
    sstResponsibleEmail: 'sst@agrosinu.com.co',
    sstResponsiblePhone: '+57 300 123 4455',

    nextFollowUpDate: '2026-09-04',
    nextFollowUpAction: 'Presentar propuesta de ahorro y plan anual de visitas SST.',
    estimatedMonthlyCommission: 241000,
    notes: 'Actualmente sin intermediario asignado en Bolívar. Requieren apoyo en auditoría 0312.',
    createdAt: '2026-08-01',
  },
  {
    id: 'lead-003',
    name: 'Metalmecánica & Diseños Industriales S.A.',
    nit: '900.231.789-0',
    economicActivity: 'Fabricación de estructuras metálicas y soldadura',
    ciiuCode: '2511',
    currentArlId: 'colmena',
    proposedArlId: 'colpatria',
    riskClass: 'CLASE_V',
    estimatedIbc: 290000000,
    employeeCount: 110,
    city: 'Manizales',
    stage: 'NUEVO_LEAD',
    source: 'LLAMADA_FRIO',
    conceptType: 'CAMBIO_INTERMEDIARIO',

    // Representante Legal
    legalRepName: 'Ing. Rodrigo Echeverry',
    legalRepEmail: 'recheverry@metalm.com.co',
    legalRepPhone: '+57 315 222 3344',

    // Responsable SST
    sstResponsibleName: 'Especialista Viviana Cardona',
    sstResponsibleEmail: 'sst@metalm.com.co',
    sstResponsiblePhone: '+57 318 999 0011',

    nextFollowUpDate: '2026-09-05',
    nextFollowUpAction: 'Enviar comparativo de cobertura AXA Colpatria vs Colmena ARL.',
    estimatedMonthlyCommission: 1815000,
    notes: 'Alto índice de accidentalidad en soldadura y corte. Valoran plan de medicina laboral.',
    createdAt: '2026-08-15',
  },
];

export const INITIAL_PILA_RECORDS: PilaRecord[] = [
  {
    id: 'pila-2026-08-001',
    clientId: 'cli-001',
    clientName: 'Constructora Andina del Caribe S.A.S.',
    month: '2026-08',
    year: 2026,
    ibcReported: 185000000,
    riskClass: 'CLASE_V',
    arlRate: 0.06960,
    arlContribution: 12876000,
    commissionPercentage: 9.0,
    expectedCommission: 1158840,
    realPaidCommission: 1158840,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'sura',
    paymentDate: '2026-08-08',
    notes: 'Pago PILA liquidado correctamente con recaudo ARL SURA confirmado.',
    retefuenteRate: 0.10,
    retefuenteAmount: 115884,
    netCommissionReceived: 1042956,
    clientReturnPercentage: 30,
    clientReturnAmount: 347652,
    agencyNetMargin: 695304,
  },
  {
    id: 'pila-2026-08-002',
    clientId: 'cli-002',
    clientName: 'Industrias Químicas del Valle S.A.',
    month: '2026-08',
    year: 2026,
    ibcReported: 320000000,
    riskClass: 'CLASE_III',
    arlRate: 0.02436,
    arlContribution: 7795200,
    commissionPercentage: 5.5,
    expectedCommission: 428736,
    realPaidCommission: 400000,
    difference: 28736,
    status: 'DIVERGENCIA',
    arlId: 'bolivar',
    paymentDate: '2026-08-05',
    notes: 'Diferencia detectada: ARL Bolívar liquidó sobre 300M de IBC (faltó sede Yumbo).',
    retefuenteRate: 0.10,
    retefuenteAmount: 40000,
    netCommissionReceived: 360000,
    clientReturnPercentage: 25,
    clientReturnAmount: 100000,
    agencyNetMargin: 260000,
  },
  {
    id: 'pila-2026-08-003',
    clientId: 'cli-003',
    clientName: 'Logística & Transportes del Norte S.A.S.',
    month: '2026-08',
    year: 2026,
    ibcReported: 142000000,
    riskClass: 'CLASE_IV',
    arlRate: 0.04350,
    arlContribution: 6177000,
    commissionPercentage: 7.2,
    expectedCommission: 444744,
    realPaidCommission: 444744,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'colpatria',
    paymentDate: '2026-08-09',
    notes: 'Planilla 94821731 conciliada sin objeción con AXA Colpatria.',
    retefuenteRate: 0.10,
    retefuenteAmount: 44474,
    netCommissionReceived: 400270,
    clientReturnPercentage: 20,
    clientReturnAmount: 88949,
    agencyNetMargin: 311321,
  },
  {
    id: 'pila-2026-08-004',
    clientId: 'cli-004',
    clientName: 'Financiera & Consultores Alianza S.A.',
    month: '2026-08',
    year: 2026,
    ibcReported: 98000000,
    riskClass: 'CLASE_I',
    arlRate: 0.00522,
    arlContribution: 511560,
    commissionPercentage: 4.5,
    expectedCommission: 23020,
    realPaidCommission: 23020,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'positiva',
    paymentDate: '2026-08-04',
    notes: 'Pago PILA al día.',
    retefuenteRate: 0.10,
    retefuenteAmount: 2302,
    netCommissionReceived: 20718,
    clientReturnPercentage: 15,
    clientReturnAmount: 3453,
    agencyNetMargin: 17265,
  },
  {
    id: 'pila-2026-08-005',
    clientId: 'cli-005',
    clientName: 'Textiles & Confecciones Bucaramanga Ltda.',
    month: '2026-08',
    year: 2026,
    ibcReported: 76000000,
    riskClass: 'CLASE_II',
    arlRate: 0.01044,
    arlContribution: 793440,
    commissionPercentage: 6.0,
    expectedCommission: 47606,
    realPaidCommission: 0,
    difference: 47606,
    status: 'MORA',
    arlId: 'colmena',
    paymentDate: undefined,
    notes: 'Empresa en mora patronal (venció el 10 de agosto). Alerta enviada por WhatsApp.',
    retefuenteRate: 0.10,
    retefuenteAmount: 0,
    netCommissionReceived: 0,
    clientReturnPercentage: 20,
    clientReturnAmount: 0,
    agencyNetMargin: 0,
  },
  // --- HISTORIAL Q3 2026 (Julio) ---
  {
    id: 'pila-2026-07-001',
    clientId: 'cli-001',
    clientName: 'Constructora Andina del Caribe S.A.S.',
    month: '2026-07',
    year: 2026,
    ibcReported: 180000000,
    riskClass: 'CLASE_V',
    arlRate: 0.06960,
    arlContribution: 12528000,
    commissionPercentage: 9.0,
    expectedCommission: 1127520,
    realPaidCommission: 1127520,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'sura',
    paymentDate: '2026-07-09',
    notes: 'Liquidación PILA Julio sin objeción.',
    retefuenteRate: 0.10,
    retefuenteAmount: 112752,
    netCommissionReceived: 1014768,
    clientReturnPercentage: 30,
    clientReturnAmount: 338256,
    agencyNetMargin: 676512,
  },
  {
    id: 'pila-2026-07-002',
    clientId: 'cli-002',
    clientName: 'Industrias Químicas del Valle S.A.',
    month: '2026-07',
    year: 2026,
    ibcReported: 310000000,
    riskClass: 'CLASE_III',
    arlRate: 0.02436,
    arlContribution: 7551600,
    commissionPercentage: 5.5,
    expectedCommission: 415338,
    realPaidCommission: 415338,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'bolivar',
    paymentDate: '2026-07-07',
    notes: 'Conciliación PILA Julio conforme a planilla.',
    retefuenteRate: 0.10,
    retefuenteAmount: 41534,
    netCommissionReceived: 373804,
    clientReturnPercentage: 25,
    clientReturnAmount: 103835,
    agencyNetMargin: 269969,
  },
  {
    id: 'pila-2026-07-003',
    clientId: 'cli-003',
    clientName: 'Logística & Transportes del Norte S.A.S.',
    month: '2026-07',
    year: 2026,
    ibcReported: 138000000,
    riskClass: 'CLASE_IV',
    arlRate: 0.04350,
    arlContribution: 6003000,
    commissionPercentage: 7.2,
    expectedCommission: 432216,
    realPaidCommission: 432216,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'colpatria',
    paymentDate: '2026-07-10',
    notes: 'Recaudo efectivo AXA Colpatria Julio.',
    retefuenteRate: 0.10,
    retefuenteAmount: 43222,
    netCommissionReceived: 388994,
    clientReturnPercentage: 20,
    clientReturnAmount: 86443,
    agencyNetMargin: 302551,
  },
  // --- HISTORIAL Q2 2026 / S1 2026 (Junio & Mayo) ---
  {
    id: 'pila-2026-06-001',
    clientId: 'cli-001',
    clientName: 'Constructora Andina del Caribe S.A.S.',
    month: '2026-06',
    year: 2026,
    ibcReported: 175000000,
    riskClass: 'CLASE_V',
    arlRate: 0.06960,
    arlContribution: 12180000,
    commissionPercentage: 9.0,
    expectedCommission: 1096200,
    realPaidCommission: 1096200,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'sura',
    paymentDate: '2026-06-10',
    notes: 'Conciliación Jun 2026 - Cierre de Semestre 1.',
    retefuenteRate: 0.10,
    retefuenteAmount: 109620,
    netCommissionReceived: 986580,
    clientReturnPercentage: 30,
    clientReturnAmount: 328860,
    agencyNetMargin: 657720,
  },
  {
    id: 'pila-2026-06-002',
    clientId: 'cli-002',
    clientName: 'Industrias Químicas del Valle S.A.',
    month: '2026-06',
    year: 2026,
    ibcReported: 300000000,
    riskClass: 'CLASE_III',
    arlRate: 0.02436,
    arlContribution: 7308000,
    commissionPercentage: 5.5,
    expectedCommission: 401940,
    realPaidCommission: 401940,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'bolivar',
    paymentDate: '2026-06-08',
    notes: 'Pago PILA Junio verificado.',
    retefuenteRate: 0.10,
    retefuenteAmount: 40194,
    netCommissionReceived: 361746,
    clientReturnPercentage: 25,
    clientReturnAmount: 100485,
    agencyNetMargin: 261261,
  },
  {
    id: 'pila-2026-05-001',
    clientId: 'cli-003',
    clientName: 'Logística & Transportes del Norte S.A.S.',
    month: '2026-05',
    year: 2026,
    ibcReported: 135000000,
    riskClass: 'CLASE_IV',
    arlRate: 0.04350,
    arlContribution: 5872500,
    commissionPercentage: 7.2,
    expectedCommission: 422820,
    realPaidCommission: 422820,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'colpatria',
    paymentDate: '2026-05-08',
    notes: 'Pago Mayo conciliado.',
    retefuenteRate: 0.10,
    retefuenteAmount: 42282,
    netCommissionReceived: 380538,
    clientReturnPercentage: 20,
    clientReturnAmount: 84564,
    agencyNetMargin: 295974,
  },
  // --- HISTORIAL Q1 2026 / S1 2026 (Marzo) ---
  {
    id: 'pila-2026-03-001',
    clientId: 'cli-001',
    clientName: 'Constructora Andina del Caribe S.A.S.',
    month: '2026-03',
    year: 2026,
    ibcReported: 165000000,
    riskClass: 'CLASE_V',
    arlRate: 0.06960,
    arlContribution: 11484000,
    commissionPercentage: 9.0,
    expectedCommission: 1033560,
    realPaidCommission: 1033560,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'sura',
    paymentDate: '2026-03-09',
    notes: 'Cierre de Trimestre 1 - Marzo 2026.',
    retefuenteRate: 0.10,
    retefuenteAmount: 103356,
    netCommissionReceived: 930204,
    clientReturnPercentage: 30,
    clientReturnAmount: 310068,
    agencyNetMargin: 620136,
  },
  {
    id: 'pila-2026-03-002',
    clientId: 'cli-004',
    clientName: 'Financiera & Consultores Alianza S.A.',
    month: '2026-03',
    year: 2026,
    ibcReported: 92000000,
    riskClass: 'CLASE_I',
    arlRate: 0.00522,
    arlContribution: 480240,
    commissionPercentage: 4.5,
    expectedCommission: 21611,
    realPaidCommission: 21611,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'positiva',
    paymentDate: '2026-03-06',
    notes: 'Pago PILA Marzo Positiva.',
    retefuenteRate: 0.10,
    retefuenteAmount: 2161,
    netCommissionReceived: 19450,
    clientReturnPercentage: 15,
    clientReturnAmount: 3242,
    agencyNetMargin: 16208,
  },
  // --- HISTORIAL AÑO 2025 (Q4 2025 / S2 2025) ---
  {
    id: 'pila-2025-11-001',
    clientId: 'cli-001',
    clientName: 'Constructora Andina del Caribe S.A.S.',
    month: '2025-11',
    year: 2025,
    ibcReported: 155000000,
    riskClass: 'CLASE_V',
    arlRate: 0.06960,
    arlContribution: 10788000,
    commissionPercentage: 9.0,
    expectedCommission: 970920,
    realPaidCommission: 970920,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'sura',
    paymentDate: '2025-11-10',
    notes: 'Histórico Anual 2025 - Noviembre.',
    retefuenteRate: 0.10,
    retefuenteAmount: 97092,
    netCommissionReceived: 873828,
    clientReturnPercentage: 30,
    clientReturnAmount: 291276,
    agencyNetMargin: 582552,
  },
  {
    id: 'pila-2025-11-002',
    clientId: 'cli-002',
    clientName: 'Industrias Químicas del Valle S.A.',
    month: '2025-11',
    year: 2025,
    ibcReported: 280000000,
    riskClass: 'CLASE_III',
    arlRate: 0.02436,
    arlContribution: 6820800,
    commissionPercentage: 5.5,
    expectedCommission: 375144,
    realPaidCommission: 375144,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'bolivar',
    paymentDate: '2025-11-08',
    notes: 'Histórico Anual 2025 - Noviembre Bolívar.',
    retefuenteRate: 0.10,
    retefuenteAmount: 37514,
    netCommissionReceived: 337630,
    clientReturnPercentage: 25,
    clientReturnAmount: 93786,
    agencyNetMargin: 243844,
  },
];

export const INITIAL_FIELD_VISITS: FieldVisit[] = [
  {
    id: 'vis-001',
    clientId: 'cli-001',
    clientName: 'Constructora Andina del Caribe S.A.S.',
    engineerId: 'eng-01',
    engineerName: 'Ing. Félix Bedoya (Lic. SST 14920)',
    visitDate: '2026-08-22',
    hoursSpent: 4.0,
    visitType: 'AUDITORIA_0312',
    standardsCount: 60,
    checklistScore: 88.5,
    findings: 'Se verificó avance satisfactorio en estándares de matriz de peligros GTC-45 y brigada de emergencias. Pendiente calibración de sonómetro para medición higiénica en taller.',
    actionPlan: '1. Programar estudio de ruido dosimétrico con ARL SURA antes del 15 de septiembre. 2. Actualizar actas de COPASST.',
    observations: 'Excelente disposición del equipo directivo. El plan de mejoramiento quedó radicado formalmente.',
    status: 'REALIZADA',
    clientSignature: 'Firmado digitalmente por Ing. Laura Marcela Osorio (SST)',
    location: 'Sede Principal - Barranquilla',
    hasCost: false,
    visitCost: 0,
    costNotes: 'Acompañamiento cubierto 100% con cargo al retorno/intermediación ARL SURA (Valor comercial equivalente: $480.000 COP sin costo directo)',
  },
  {
    id: 'vis-002',
    clientId: 'cli-002',
    clientName: 'Industrias Químicas del Valle S.A.',
    engineerId: 'eng-01',
    engineerName: 'Ing. Félix Bedoya (Lic. SST 14920)',
    visitDate: '2026-08-25',
    hoursSpent: 6.5,
    visitType: 'MATRIZ_PELIGROS',
    standardsCount: 60,
    checklistScore: 92.0,
    findings: 'Revisión técnica de hojas de seguridad (SGA) en reactores de síntesis. Sistema de ventilación forzada en buen estado de operación.',
    actionPlan: 'Capacitar a 18 nuevos operarios en manejo de sustancias corrosivas y kits antiderrames.',
    observations: 'Auditoría en planta de reactores químicos completada sin novedades críticas.',
    status: 'REALIZADA',
    clientSignature: 'Firmado digitalmente por Ing. Mauricio Gómez (SST)',
    location: 'Planta Yumbo - Valle del Cauca',
    hasCost: false,
    visitCost: 0,
    costNotes: 'Cubierto 100% por bolsa de reinversión ARL Bolívar (Valor comercial equivalente: $780.000 COP)',
  },
  {
    id: 'vis-003',
    clientId: 'cli-003',
    clientName: 'Logística & Transportes del Norte S.A.S.',
    engineerId: 'eng-01',
    engineerName: 'Ing. Félix Bedoya (Lic. SST 14920)',
    visitDate: '2026-08-28',
    hoursSpent: 3.5,
    visitType: 'ERGONOMICA',
    standardsCount: 21,
    checklistScore: 78.0,
    findings: 'Evaluación postural RULA en operarios de cargue manual arrojó nivel de acción 3 (se requiere intervención ergonómica).',
    actionPlan: 'Adquisición de 2 transpaletas hidráulicas de apoyo e implementar pausas activas osteomusculares.',
    observations: 'Pendiente entrega de cotización de transpaletas y validación del cronograma de pausas activas.',
    status: 'PENDIENTE',
    location: 'Bodega Principal - Guarne / Medellín',
    hasCost: false,
    visitCost: 0,
    costNotes: 'Cubierto por acompañamiento pactado con ARL AXA Colpatria',
  },
  {
    id: 'vis-004',
    clientId: 'cli-004',
    clientName: 'Financiera & Consultores Alianza S.A.',
    engineerId: 'eng-01',
    engineerName: 'Ing. Félix Bedoya (Lic. SST 14920)',
    visitDate: '2026-09-08',
    hoursSpent: 3.0,
    visitType: 'INSPECCION_SEGURIDAD',
    findings: 'Inspección programada de puestos de trabajo, pantallas de visualización de datos (PVD) y condiciones de iluminación.',
    actionPlan: 'Levantamiento de matriz ergonómica y reporte de recomendaciones para el personal administrativo.',
    observations: 'Visita confirmada con Recursos Humanos y Responsable SST (Dra. Claudia Ortiz).',
    status: 'PROGRAMADA',
    location: 'Sede Financiera - Carrera 7 No. 72-10 Bogotá',
    hasCost: true,
    visitCost: 360000,
    costNotes: 'Asesoría técnica valorizada en $360.000 COP (3 horas a $120.000/hr)',
  },
  {
    id: 'vis-005',
    clientId: 'cli-001',
    clientName: 'Constructora Andina del Caribe S.A.S.',
    engineerId: 'eng-01',
    engineerName: 'Ing. Laura Marcela Osorio (SST)',
    visitDate: '2026-09-12',
    hoursSpent: 4.5,
    visitType: 'CAPACITACION',
    findings: 'Jornada programada de reentrenamiento en Trabajo Seguro en Alturas (Res. 4272/2021) e inspección de arneses.',
    actionPlan: 'Inspeccionar 35 equipos contra caídas y expedir certificados de aptitud técnica.',
    observations: 'Coordinado con ARL SURA para suministro de kit de rescate vertical demostrativo.',
    status: 'PROGRAMADA',
    location: 'Frente de Obra Torre Mar - Barranquilla',
    hasCost: false,
    visitCost: 0,
    costNotes: 'Jornada de reentrenamiento cubierta 100% por intermediación ARL',
  },
  {
    id: 'vis-006',
    clientId: 'cli-005',
    clientName: 'Textiles & Confecciones Bucaramanga Ltda.',
    engineerId: 'eng-01',
    engineerName: 'Ing. Diego Rueda',
    visitDate: '2026-08-30',
    hoursSpent: 2.5,
    visitType: 'INSPECCION_SEGURIDAD',
    findings: 'Inspección de guardas de seguridad en 14 máquinas de coser industriales y rutas de evacuación en taller de confección.',
    actionPlan: 'Instalar protectores de aguja faltantes en 3 máquinas y despejar extintor de pasillo 2.',
    observations: 'Informe preliminar redactado. Pendiente firma y recepción de carta de compromiso gerencial.',
    status: 'PENDIENTE',
    location: 'Planta de Confección - Bucaramanga',
    hasCost: false,
    visitCost: 0,
    costNotes: 'Cubierto 100% por bolsa de retorno acordada con la empresa',
  },
];

export const INITIAL_MEDICAL_RECORDS: MedicalRecord[] = [
  {
    id: 'med-001',
    clientId: 'cli-001',
    clientName: 'Constructora Andina del Caribe S.A.S.',
    incidentType: 'ACCIDENTE_TRABAJO',
    employeeDocument: 'CC 1.047.882.119',
    employeeName: 'Jhonny Alexander Pérez',
    employeeRole: 'Ayudante de Obra',
    diagnosisCie10: 'S61.0',
    diagnosisDescription: 'Herida abierta de dedo de la mano sin daño de la uña (atrapamiento con formaleta)',
    daysLost: 4,
    furatFurepCode: 'FURAT-2026-98124',
    pveProgram: 'NINGUNO',
    medicalNotes: 'Manejo ambulatorio con sutura y curaciones. Reintegro con recomendaciones laborales de no levantar peso con mano izquierda por 7 días.',
    confidentialFlag: false,
    date: '2026-08-14',
    createdByDoctor: 'Dra. Marcela Salazar (Médico Laboral - Reg. Médico 8841)',
  },
  {
    id: 'med-002',
    clientId: 'cli-002',
    clientName: 'Industrias Químicas del Valle S.A.',
    incidentType: 'AUSENTISMO_COMUN',
    employeeDocument: 'CC 66.890.123',
    employeeName: 'María Fernanda Henao',
    employeeRole: 'Analista de Control de Calidad',
    diagnosisCie10: 'M54.5',
    diagnosisDescription: 'Lumbago no especificado',
    daysLost: 3,
    pveProgram: 'OSTEOMUSCULAR',
    medicalNotes: 'Ingresada a PVE Osteomuscular. Se remite para valoración por fisioterapia y ajuste de silla ergonómica en laboratorio.',
    confidentialFlag: false,
    date: '2026-08-18',
    createdByDoctor: 'Dra. Marcela Salazar (Médico Laboral - Reg. Médico 8841)',
  },
  {
    id: 'med-003',
    clientId: 'cli-003',
    clientName: 'Logística & Transportes del Norte S.A.S.',
    incidentType: 'EXAMEN_MEDICO',
    employeeDocument: 'CC 98.712.345',
    employeeName: 'Rodrigo Osorio',
    employeeRole: 'Conductor de Tractomula',
    diagnosisCie10: 'Z10.0',
    diagnosisDescription: 'Examen de salud ocupacional periódico anual',
    daysLost: 0,
    pveProgram: 'CARDIOVASCULAR',
    medicalNotes: 'Apto con recomendaciones: control de perfil lipídico y programa de hábitos de vida saludable.',
    confidentialFlag: false,
    date: '2026-08-20',
    createdByDoctor: 'Dra. Marcela Salazar (Médico Laboral - Reg. Médico 8841)',
  },
  {
    id: 'med-004',
    clientId: 'cli-001',
    clientName: 'Constructora Andina del Caribe S.A.S.',
    incidentType: 'ACCIDENTE_TRABAJO',
    employeeDocument: 'CC 1.098.765.432',
    employeeName: 'Carlos Mario Benítez',
    employeeRole: 'Oficial de Estructuras y Fierrería',
    diagnosisCie10: 'S93.4',
    diagnosisDescription: 'Esguince y torcedura del tobillo por tropiezo con varilla',
    daysLost: 7,
    furatFurepCode: 'FURAT-2026-99341',
    pveProgram: 'NINGUNO',
    medicalNotes: 'Inmovilización con férula elástica y reposo médico. Investigación de AT realizada por COPASST.',
    confidentialFlag: false,
    date: '2026-08-26',
    createdByDoctor: 'Dra. Marcela Salazar (Médico Laboral - Reg. Médico 8841)',
  },
  {
    id: 'med-005',
    clientId: 'cli-002',
    clientName: 'Industrias Químicas del Valle S.A.',
    incidentType: 'ENFERMEDAD_LABORAL',
    employeeDocument: 'CC 31.456.789',
    employeeName: 'Luz Marina Caicedo',
    employeeRole: 'Operaria de Envasado y Empaque',
    diagnosisCie10: 'G56.0',
    diagnosisDescription: 'Síndrome del túnel carpiano bilateral (Calificación en estudio)',
    daysLost: 5,
    furatFurepCode: 'FUREL-2026-1102',
    pveProgram: 'OSTEOMUSCULAR',
    medicalNotes: 'Caso remitido a Junta Regional de Calificación. Ingreso prioritario a PVE Biomecánico y rotación de puesto.',
    confidentialFlag: false,
    date: '2026-08-29',
    createdByDoctor: 'Dra. Marcela Salazar (Médico Laboral - Reg. Médico 8841)',
  },
  {
    id: 'med-006',
    clientId: 'cli-005',
    clientName: 'Textiles & Confecciones Bucaramanga Ltda.',
    incidentType: 'AUSENTISMO_COMUN',
    employeeDocument: 'CC 63.512.980',
    employeeName: 'Yolanda Suárez',
    employeeRole: 'Costurera de Confección',
    diagnosisCie10: 'J06.9',
    diagnosisDescription: 'Infección aguda de las vías respiratorias superiores',
    daysLost: 2,
    pveProgram: 'RESPIRATORIO',
    medicalNotes: 'Incapacidad médica por EPS Sanitas. Reintegro normal sin secuelas.',
    confidentialFlag: false,
    date: '2026-08-30',
    createdByDoctor: 'Dra. Marcela Salazar (Médico Laboral - Reg. Médico 8841)',
  }
];

export const INITIAL_RUI_PROFILE: RUIIntermediaryProfile = {
  registrationNumber: 'RUI-MINTRABAJO-2024-8849',
  agencyName: 'PRAXIS PREVENCIÓN Y SEGUROS AGENCIA DE SEGUROS LTDA.',
  nit: '901.884.200-1',
  legalRepresentative: 'Félix Bedoya',
  technicalDoctorName: 'Dra. Marcela Salazar Botero',
  technicalDoctorLicense: 'Licencia SST Res. 4192 / Reg. Médico 8841',
  technicalEngineerName: 'Ing. Félix Bedoya',
  technicalEngineerLicense: 'Licencia SST Res. 14920 / COPNIA 25202-0941',
  legalAdvisorName: 'Dr. Alejandro Vargas Quintero',
  legalAdvisorCard: 'Tarjeta Profesional C.S.J. 219.840',
  insurancePolicyNumber: 'POL-RC-SEGUROS-994821',
  insurancePolicyCompany: 'Seguros del Estado S.A.',
  policyExpiryDate: '2027-04-30',
  totalCertifiedHours: 420.5,
};

export const INITIAL_WHATSAPP_MESSAGES: WhatsAppMessage[] = [
  {
    id: 'wapp-001',
    recipientPhone: '+573104458899',
    recipientName: 'Carlos Mendoza',
    companyName: 'Constructora Andina del Caribe S.A.S.',
    messageType: 'ALERTA_PILA',
    content: 'Estimado Carlos, te confirmamos que la planilla PILA de agosto por $12,876,000 con ARL SURA fue radicada y validada con éxito.',
    timestamp: '2026-08-08 09:30',
    status: 'LEIDO',
    direction: 'OUTBOUND',
  },
  {
    id: 'wapp-002',
    recipientPhone: '+573184321098',
    recipientName: 'Gustavo Plata',
    companyName: 'Textiles & Confecciones Bucaramanga Ltda.',
    messageType: 'ALERTA_MORA',
    content: 'Estimado Gustavo, te recordamos que el pago de la planilla ARL de agosto se encuentra pendiente en Colmena Seguros.',
    timestamp: '2026-08-11 10:15',
    status: 'ENTREGADO',
    direction: 'OUTBOUND',
  },
];

export const INITIAL_AGENCY_PROFILE: AgencyProfile = {
  name: 'PRAXIS PREVENCIÓN Y SEGUROS AGENCIA DE SEGUROS LTDA.',
  shortName: 'PRAXIS',
  suffix: 'LTDA',
  tagline: 'Prevención y Seguros',
  nit: '901.884.200-1',
  ruiNumber: 'RUI-MINTRABAJO-2024-8849',
  logoUrl: '/praxis-logo.png',
  phone: '(+57) 314 884 9200',
  email: 'gerencia@praxisprevencion.com',
  city: 'Bogotá D.C.',
  address: 'Calle 100 # 19-61 Edificio Capital Tower Of. 802',
};

export const INITIAL_USER_PROFILES: UserProfile[] = [
  {
    id: 'user-admin',
    name: 'Félix Bedoya',
    roleTitle: 'Director Técnico SST & Administrador',
    roleType: 'ADMIN',
    licenseSST: 'Licencia SST Res. 14920 / COPNIA 25202',
    email: 'felix.bedoya@praxisprevencion.com',
    phone: '+57 314 884 9200',
    initials: 'FB',
  },
  {
    id: 'user-medico',
    name: 'Dra. Marcela Salazar',
    roleTitle: 'Médico Especialista Laboral',
    roleType: 'MEDICO_LABORAL',
    licenseSST: 'Reg. Médico 8841 / Lic. SST 4192',
    email: 'marcela.salazar@praxisprevencion.com',
    phone: '+57 310 994 1122',
    initials: 'MS',
  },
  {
    id: 'user-financiero',
    name: 'Santiago Arango',
    roleTitle: 'Analista de Comisiones & Cartera PILA',
    roleType: 'ANALISTA_FINANCIERO',
    licenseSST: 'T.P. Contador 198422',
    email: 'comisiones@praxisprevencion.com',
    phone: '+57 300 552 4433',
    initials: 'SA',
  },
  {
    id: 'user-comercial',
    name: 'Carolina Restrepo',
    roleTitle: 'Gerente de Cuentas & Prospección ARL',
    roleType: 'ASESOR_COMERCIAL',
    licenseSST: 'Id Broker ARL 4492',
    email: 'comercial@praxisprevencion.com',
    phone: '+57 315 220 7788',
    initials: 'CR',
  },
];
