import { ARLCompany, ClientCompany, LeadProspect, PilaRecord, FieldVisit, MedicalRecord, RUIIntermediaryProfile, WhatsAppMessage, UserProfile, AgencyProfile, OccupationalExam, ExamCatalogItem } from '@/types';

export const INITIAL_ARLS: ARLCompany[] = [
  {
    id: 'positiva',
    name: 'Positiva Compañía de Seguros S.A.',
    shortName: 'Positiva ARL',
    superintendenciaCode: '14-23',
    phone: '018000 111 170',
    website: 'https://www.positiva.gov.co',
    colorTheme: '#D97706',
    logo: '🛡️',
    status: 'ACTIVA',
    commissionRegime: 'GASTOS_ADMINISTRACION',
    notes: 'ARL estatal con amplia cobertura en sector público, educación, manufactura y calzado.',
    defaultCommissionMatrix: {
      EMPRESA_NUEVA: { CLASE_I: 7.5, CLASE_II: 8.0, CLASE_III: 8.5, CLASE_IV: 8.5, CLASE_V: 8.5 },
      NOMBRAMIENTO: { CLASE_I: 5.5, CLASE_II: 6.0, CLASE_III: 6.5, CLASE_IV: 7.0, CLASE_V: 7.5 },
      CAMBIO_INTERMEDIARIO: { CLASE_I: 6.5, CLASE_II: 7.0, CLASE_III: 7.5, CLASE_IV: 8.0, CLASE_V: 8.0 },
    },
    economicActivityCommissions: [
      { id: 'pos-act-1', riskClass: 'CLASE_V', ciiuCode: '4111', activityName: 'Construcción de edificios residenciales', commissionRate: 8.5, notes: 'Tarifa preferencial para agremiaciones constructoras' },
      { id: 'pos-act-2', riskClass: 'CLASE_V', ciiuCode: '0510', activityName: 'Extracción de hulla (carbón de piedra)', commissionRate: 9.0, notes: 'Minería subterránea bajo convenio' },
      { id: 'pos-act-3', riskClass: 'CLASE_IV', ciiuCode: '4923', activityName: 'Transporte de carga por carretera', commissionRate: 8.5, notes: 'Flotas de carga pesada' },
      { id: 'pos-act-4', riskClass: 'CLASE_III', ciiuCode: '1521', activityName: 'Fabricación de calzado de seguridad y cuero', commissionRate: 8.5, notes: 'Sector manufactura de calzado industrial' },
      { id: 'pos-act-5', riskClass: 'CLASE_I', ciiuCode: '8411', activityName: 'Actividades de administración general', commissionRate: 8.0, notes: 'Entidades corporativas' },
    ],
  },
  {
    id: 'sura',
    name: 'Seguros de Vida Suramericana S.A. (ARL SURA)',
    shortName: 'ARL SURA',
    superintendenciaCode: '14-18',
    phone: '018000 511 414',
    website: 'https://www.segurossura.com.co',
    colorTheme: '#0033A0',
    logo: '🐯',
    status: 'ACTIVA',
    commissionRegime: 'GASTOS_ADMINISTRACION',
    notes: 'Líder en prevención técnica y reconocimiento puntual de intermediación (Ley 1562/2012).',
    defaultCommissionMatrix: {
      EMPRESA_NUEVA: { CLASE_I: 8.0, CLASE_II: 8.5, CLASE_III: 9.0, CLASE_IV: 9.0, CLASE_V: 9.0 },
      NOMBRAMIENTO: { CLASE_I: 6.0, CLASE_II: 6.5, CLASE_III: 7.0, CLASE_IV: 7.5, CLASE_V: 8.0 },
      CAMBIO_INTERMEDIARIO: { CLASE_I: 7.0, CLASE_II: 7.5, CLASE_III: 8.0, CLASE_IV: 8.5, CLASE_V: 9.0 },
    },
    economicActivityCommissions: [
      { id: 'sur-act-1', riskClass: 'CLASE_V', ciiuCode: '4111', activityName: 'Construcción de edificios y obras civiles', commissionRate: 9.5, notes: 'Tasa especial para constructoras AAA con PVE' },
      { id: 'sur-act-2', riskClass: 'CLASE_IV', ciiuCode: '4923', activityName: 'Transporte de carga por carretera', commissionRate: 9.0, notes: 'Convenio logístico empresarial' },
      { id: 'sur-act-3', riskClass: 'CLASE_III', ciiuCode: '0126', activityName: 'Cultivo de palma para aceite y agroindustria', commissionRate: 8.5, notes: 'Sector agroindustrial de palma' },
      { id: 'sur-act-4', riskClass: 'CLASE_I', ciiuCode: '6412', activityName: 'Bancos comerciales y actividades financieras', commissionRate: 8.0, notes: 'Sector corporativo financiero' },
    ],
  },
  {
    id: 'bolivar',
    name: 'Seguros Bolívar S.A.',
    shortName: 'ARL Bolívar',
    superintendenciaCode: '14-25',
    phone: '018000 123 322',
    website: 'https://www.segurosbolivar.com',
    colorTheme: '#059669',
    logo: '🟢',
    status: 'ACTIVA',
    commissionRegime: 'GASTOS_ADMINISTRACION',
    notes: 'Especialista en constructoras, obras de infraestructura y transporte.',
    defaultCommissionMatrix: {
      EMPRESA_NUEVA: { CLASE_I: 8.0, CLASE_II: 8.5, CLASE_III: 9.0, CLASE_IV: 9.0, CLASE_V: 9.0 },
      NOMBRAMIENTO: { CLASE_I: 5.5, CLASE_II: 6.0, CLASE_III: 6.5, CLASE_IV: 7.0, CLASE_V: 7.5 },
      CAMBIO_INTERMEDIARIO: { CLASE_I: 7.0, CLASE_II: 7.5, CLASE_III: 8.0, CLASE_IV: 8.5, CLASE_V: 8.5 },
    },
    economicActivityCommissions: [
      { id: 'bol-act-1', riskClass: 'CLASE_V', ciiuCode: '4111', activityName: 'Construcción de edificios residenciales y comerciales', commissionRate: 9.2, notes: 'Infraestructura y proyectos verticales' },
      { id: 'bol-act-2', riskClass: 'CLASE_IV', ciiuCode: '4923', activityName: 'Transporte de carga terrestre nacional', commissionRate: 8.8, notes: 'Logística de carga pesada' },
      { id: 'bol-act-3', riskClass: 'CLASE_I', ciiuCode: '8211', activityName: 'Servicios combinados de gestión administrativa', commissionRate: 8.0, notes: 'Sedes centrales' },
    ],
  },
  {
    id: 'colpatria',
    name: 'AXA Colpatria Seguros de Vida S.A.',
    shortName: 'AXA Colpatria',
    superintendenciaCode: '14-04',
    phone: '018000 512 620',
    website: 'https://www.axacolpatria.co',
    colorTheme: '#DC2626',
    logo: '🔷',
    status: 'ACTIVA',
    commissionRegime: 'GASTOS_ADMINISTRACION',
    notes: 'Fuerte en sector hidrocarburos, montajes metalmecánicos y comercio masivo.',
    defaultCommissionMatrix: {
      EMPRESA_NUEVA: { CLASE_I: 8.0, CLASE_II: 8.5, CLASE_III: 9.0, CLASE_IV: 9.0, CLASE_V: 9.0 },
      NOMBRAMIENTO: { CLASE_I: 6.0, CLASE_II: 6.5, CLASE_III: 7.2, CLASE_IV: 7.5, CLASE_V: 8.0 },
      CAMBIO_INTERMEDIARIO: { CLASE_I: 7.0, CLASE_II: 7.5, CLASE_III: 8.0, CLASE_IV: 8.5, CLASE_V: 9.0 },
    },
    economicActivityCommissions: [
      { id: 'colp-act-1', riskClass: 'CLASE_V', ciiuCode: '2511', activityName: 'Fabricación de estructuras metálicas y tubería pesada', commissionRate: 9.0, notes: 'Metalmecánica industrial y montajes' },
      { id: 'colp-act-2', riskClass: 'CLASE_IV', ciiuCode: '5229', activityName: 'Otras actividades de apoyo al transporte y patios', commissionRate: 8.5, notes: 'Operaciones de patio' },
      { id: 'colp-act-3', riskClass: 'CLASE_I', ciiuCode: '7112', activityName: 'Actividades de ingeniería y consultoría técnica', commissionRate: 8.0, notes: 'Oficinas de proyectos' },
    ],
  },
];

// =========================================================================
// 5 EMPRESAS DEL ECOSISTEMA PRAXIS EN TODOS LOS PROCESOS:
// 1. LOGÍSTICA & DISTRIBUCIÓN ANDINA S.A.S. (En Contacto / Diagnóstico)
// 2. CONSTRUCCIONES & ESTRUCTURAS DEL CARIBE S.A.S. (En Carta de Nombramiento)
// 3. AGROINDUSTRIAL PALMAREAL DEL LLANO S.A.S. (Afiliada con PILA y Retornos)
// 4. MANUFACTURAS & CALZADO INDUSTRIAL COLOMBIA S.A.S. (Con Visitas SST y Res. 0312)
// 5. METALMECÁNICA & MONTAJES PETROLEROS S.A.S. (Con Casos Médicos, AT y Ausentismo)
// =========================================================================

export const INITIAL_LEADS: LeadProspect[] = [
  // EMPRESA 1: EN PRIMER CONTACTO / DIAGNÓSTICO
  {
    id: 'lead-001',
    name: 'Logística & Distribución Andina S.A.S.',
    nit: '901.458.712-3',
    economicActivity: 'Transporte de carga por carretera y distribución logística regional',
    ciiuCode: '4923',
    currentArlId: 'positiva',
    proposedArlId: 'sura',
    riskClass: 'CLASE_IV',
    estimatedIbc: 100000000,
    employeeCount: 57,
    city: 'Cali',
    stage: 'NUEVO_LEAD',
    source: 'REFERIDO',
    conceptType: 'CAMBIO_INTERMEDIARIO',
    workCenters: [
      {
        id: 'wc-lead-1-1',
        name: 'Patio de Maniobras & Flota de Transporte',
        riskClass: 'CLASE_IV',
        employeeCount: 45,
        monthlyIbc: 78000000,
        city: 'Yumbo'
      },
      {
        id: 'wc-lead-1-2',
        name: 'Centro de Despacho & Gestión Administrativa',
        riskClass: 'CLASE_I',
        employeeCount: 12,
        monthlyIbc: 22000000,
        city: 'Cali'
      }
    ],
    legalRepName: 'Álvaro José Carvajal Osorio',
    legalRepEmail: 'gerencia@logisticaandina.com.co',
    legalRepPhone: '+57 316 450 9988',
    sstResponsibleName: 'Liliana Morales Ríos',
    sstResponsibleEmail: 'sst@logisticaandina.com.co',
    sstResponsiblePhone: '+57 317 234 5511',
    nextFollowUpDate: '2026-09-18',
    nextFollowUpAction: 'Presentación de propuesta técnica comparativa ARL SURA vs Positiva y plan de fatiga',
    estimatedMonthlyCommission: 315000,
    returnPercentage: 25,
    notes: 'Prospecto en etapa de contacto inicial. Buscan asesoría especializada en PESV (Plan Estratégico de Seguridad Vial) y retorno del 25% para bolsa técnica de capacitaciones.',
    createdAt: '2026-09-02',
  },

  // EMPRESA 2: EN CARTA DE NOMBRAMIENTO / TRÁMITE DE TRASLADO
  {
    id: 'lead-002',
    name: 'Construcciones & Estructuras del Caribe S.A.S.',
    nit: '900.892.341-9',
    economicActivity: 'Construcción de edificios residenciales y obras de urbanismo',
    ciiuCode: '4111',
    currentArlId: 'colpatria',
    proposedArlId: 'bolivar',
    riskClass: 'CLASE_V',
    estimatedIbc: 180000000,
    employeeCount: 100,
    city: 'Barranquilla',
    stage: 'CARTA_NOMBRAMIENTO',
    source: 'EVENTO_SST',
    conceptType: 'CAMBIO_INTERMEDIARIO',
    workCenters: [
      {
        id: 'wc-lead-2-1',
        name: 'Obra Proyecto Residencial Torres del Parque',
        riskClass: 'CLASE_V',
        employeeCount: 85,
        monthlyIbc: 145000000,
        city: 'Barranquilla'
      },
      {
        id: 'wc-lead-2-2',
        name: 'Sede Administrativa & Sala de Ventas',
        riskClass: 'CLASE_I',
        employeeCount: 15,
        monthlyIbc: 35000000,
        city: 'Barranquilla'
      }
    ],
    legalRepName: 'Carlos Alberto Mendoza Vega',
    legalRepEmail: 'c.mendoza@estructurascaribe.co',
    legalRepPhone: '+57 315 889 0022',
    sstResponsibleName: 'Arq. Javier Enrique Solano',
    sstResponsibleEmail: 'seguridad@estructurascaribe.co',
    sstResponsiblePhone: '+57 318 456 7789',
    nextFollowUpDate: '2026-09-14',
    nextFollowUpAction: 'Radicación de Carta de Nombramiento firmada ante ARL Bolívar y MinTrabajo',
    estimatedMonthlyCommission: 870000,
    returnPercentage: 25,
    notes: 'Carta de nombramiento generada y en proceso de firma digital por el representante legal. Traslado por insatisfacción con el acompañamiento en trabajo en alturas de la ARL anterior.',
    createdAt: '2026-08-20',
  }
];

export const INITIAL_CLIENTS: ClientCompany[] = [
  // EMPRESA 3: AFILIADA ACTIVA - ENFOQUE EN PILA Y CONCILIACIÓN DE RETORNOS
  {
    id: 'cli-001',
    nit: '860.523.890-4',
    name: 'Agroindustrial Palmareal del Llano S.A.S.',
    economicActivity: 'Cultivo de palma para aceite y extracción agroindustrial',
    ciiuCode: '0126',
    primaryArlId: 'sura',
    riskClass: 'CLASE_III',
    monthlyIbc: 110000000,
    employeeCount: 66,
    address: 'Km 14 Vía Puerto López, Vereda El Amparo',
    city: 'Villavicencio',
    conceptType: 'CAMBIO_INTERMEDIARIO',
    status: 'ACTIVO',
    returnPercentage: 25,
    workCenters: [
      {
        id: 'wc-001-1',
        name: 'Planta Extractora de Aceite & Talleres Agrícolas',
        ciiuCode: '1040',
        riskClass: 'CLASE_III',
        employeeCount: 52,
        monthlyIbc: 85000000,
        city: 'Villavicencio'
      },
      {
        id: 'wc-001-2',
        name: 'Sede Administrativa & Comercial',
        ciiuCode: '8211',
        riskClass: 'CLASE_I',
        employeeCount: 14,
        monthlyIbc: 25000000,
        city: 'Villavicencio'
      }
    ],
    legalRepName: 'María Fernanda Gómez Rincón',
    legalRepEmail: 'gerencia@palmarealllano.com.co',
    legalRepPhone: '+57 311 458 9210',
    sstResponsibleName: 'Ing. Diego Fernando Pardo',
    sstResponsibleEmail: 'sst@palmarealllano.com.co',
    sstResponsiblePhone: '+57 315 782 1430',
    sstResponsibleLicense: 'Licencia SST Res. 8412',
    standardsCount: 60,
    standardsScore: 92.0,
    standardsRating: 'ACEPTABLE',
    lastStandardsAuditDate: '2026-07-15',
    createdAt: '2026-05-10',
  },

  // EMPRESA 4: AFILIADA ACTIVA - ENFOQUE EN VISITAS DE CAMPO SST Y RES. 0312
  {
    id: 'cli-002',
    nit: '900.671.234-8',
    name: 'Manufacturas & Calzado Industrial Colombia S.A.S.',
    economicActivity: 'Fabricación de calzado de seguridad y artículos de cuero',
    ciiuCode: '1521',
    primaryArlId: 'positiva',
    riskClass: 'CLASE_III',
    monthlyIbc: 100000000,
    employeeCount: 60,
    address: 'Zona Industrial Chimitá, Calle 15 # 22-40',
    city: 'Bucaramanga',
    conceptType: 'EMPRESA_NUEVA',
    status: 'ACTIVO',
    returnPercentage: 25,
    workCenters: [
      {
        id: 'wc-002-1',
        name: 'Planta Principal de Prensas, Troquelado y Vulcanizado',
        ciiuCode: '1521',
        riskClass: 'CLASE_III',
        employeeCount: 38,
        monthlyIbc: 62000000,
        city: 'Bucaramanga'
      },
      {
        id: 'wc-002-2',
        name: 'Centro de Almacenamiento, Empaque y Envíos',
        ciiuCode: '5210',
        riskClass: 'CLASE_II',
        employeeCount: 12,
        monthlyIbc: 20000000,
        city: 'Girón'
      },
      {
        id: 'wc-002-3',
        name: 'Oficinas Administrativas y Gerencia',
        ciiuCode: '8211',
        riskClass: 'CLASE_I',
        employeeCount: 10,
        monthlyIbc: 18000000,
        city: 'Bucaramanga'
      }
    ],
    legalRepName: 'Andrés Felipe Serrano Silva',
    legalRepEmail: 'gerencia@calzadoindustrial.com.co',
    legalRepPhone: '+57 310 892 4411',
    sstResponsibleName: 'Espec. Diana Marcela Celis',
    sstResponsibleEmail: 'seguridad@calzadoindustrial.com.co',
    sstResponsiblePhone: '+57 318 672 3390',
    sstResponsibleLicense: 'Licencia SST Res. 9934',
    standardsCount: 60,
    standardsScore: 86.5,
    standardsRating: 'MODERADAMENTE_ACEPTABLE',
    lastStandardsAuditDate: '2026-08-12',
    createdAt: '2026-06-01',
  },

  // EMPRESA 5: AFILIADA ACTIVA - ENFOQUE EN CASOS MÉDICOS, AT Y AUSENTISMO
  {
    id: 'cli-003',
    nit: '830.145.987-1',
    name: 'Metalmecánica & Montajes Petroleros S.A.S.',
    economicActivity: 'Fabricación de estructuras metálicas, calderería y tubería pesada',
    ciiuCode: '2511',
    primaryArlId: 'colpatria',
    riskClass: 'CLASE_V',
    monthlyIbc: 125000000,
    employeeCount: 52,
    address: 'Vía Corregimiento El Centro Km 7',
    city: 'Barrancabermeja',
    conceptType: 'CAMBIO_INTERMEDIARIO',
    status: 'ACTIVO',
    returnPercentage: 30,
    workCenters: [
      {
        id: 'wc-003-1',
        name: 'Taller Central de Maestranza, Corte y Soldadura Pesada',
        ciiuCode: '2511',
        riskClass: 'CLASE_V',
        employeeCount: 40,
        monthlyIbc: 95000000,
        city: 'Barrancabermeja'
      },
      {
        id: 'wc-003-2',
        name: 'Oficina Técnica de Ingeniería, Diseño y Proyectos',
        ciiuCode: '7112',
        riskClass: 'CLASE_I',
        employeeCount: 12,
        monthlyIbc: 30000000,
        city: 'Barrancabermeja'
      }
    ],
    legalRepName: 'Ing. Hernán Darío Jaramillo Ortiz',
    legalRepEmail: 'hjaramillo@montajespetroleros.com.co',
    legalRepPhone: '+57 314 562 8901',
    sstResponsibleName: 'Ing. Paola Andrea Bustamante',
    sstResponsibleEmail: 'hse@montajespetroleros.com.co',
    sstResponsiblePhone: '+57 312 904 1177',
    sstResponsibleLicense: 'Licencia SST Res. 7721',
    standardsCount: 60,
    standardsScore: 81.0,
    standardsRating: 'MODERADAMENTE_ACEPTABLE',
    lastStandardsAuditDate: '2026-08-16',
    createdAt: '2026-04-15',
  }
];

export const INITIAL_PILA_RECORDS: PilaRecord[] = [
  // --- PALMAREAL DEL LLANO (cli-001) ---
  {
    id: 'pila-001',
    clientId: 'cli-001',
    clientName: 'Agroindustrial Palmareal del Llano S.A.S.',
    month: '2026-08',
    year: 2026,
    ibcReported: 112000000,
    riskClass: 'CLASE_III',
    arlRate: 0.0210,
    arlContribution: 2352000,
    commissionPercentage: 8.5,
    expectedCommission: 199920,
    realPaidCommission: 199920,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'sura',
    paymentDate: '2026-08-07',
    notes: 'Planilla PILA No. 8991204 conciliada contra liquidación ARL SURA al 100%.',
    retefuenteRate: 0.10,
    retefuenteAmount: 19992,
    netCommissionReceived: 179928,
    clientReturnPercentage: 25,
    clientReturnAmount: 49980,
    agencyNetMargin: 129948,
  },
  {
    id: 'pila-002',
    clientId: 'cli-001',
    clientName: 'Agroindustrial Palmareal del Llano S.A.S.',
    month: '2026-07',
    year: 2026,
    ibcReported: 115000000,
    riskClass: 'CLASE_III',
    arlRate: 0.0210,
    arlContribution: 2415000,
    commissionPercentage: 8.5,
    expectedCommission: 205275,
    realPaidCommission: 205275,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'sura',
    paymentDate: '2026-07-08',
    notes: 'Planilla PILA No. 8841029 pagada y validada.',
    retefuenteRate: 0.10,
    retefuenteAmount: 20528,
    netCommissionReceived: 184747,
    clientReturnPercentage: 25,
    clientReturnAmount: 51319,
    agencyNetMargin: 133428,
  },
  {
    id: 'pila-003',
    clientId: 'cli-001',
    clientName: 'Agroindustrial Palmareal del Llano S.A.S.',
    month: '2026-06',
    year: 2026,
    ibcReported: 110000000,
    riskClass: 'CLASE_III',
    arlRate: 0.0210,
    arlContribution: 2310000,
    commissionPercentage: 8.5,
    expectedCommission: 196350,
    realPaidCommission: 196350,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'sura',
    paymentDate: '2026-06-09',
    notes: 'Planilla PILA No. 8710924 conciliada.',
    retefuenteRate: 0.10,
    retefuenteAmount: 19635,
    netCommissionReceived: 176715,
    clientReturnPercentage: 25,
    clientReturnAmount: 49088,
    agencyNetMargin: 127627,
  },

  // --- CALZADO INDUSTRIAL COLOMBIA (cli-002) ---
  {
    id: 'pila-004',
    clientId: 'cli-002',
    clientName: 'Manufacturas & Calzado Industrial Colombia S.A.S.',
    month: '2026-08',
    year: 2026,
    ibcReported: 102000000,
    riskClass: 'CLASE_III',
    arlRate: 0.0185,
    arlContribution: 1887000,
    commissionPercentage: 8.5,
    expectedCommission: 160395,
    realPaidCommission: 160395,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'positiva',
    paymentDate: '2026-08-06',
    notes: 'Planilla PILA No. 9012440 validada contra extracto Positiva ARL.',
    retefuenteRate: 0.10,
    retefuenteAmount: 16040,
    netCommissionReceived: 144355,
    clientReturnPercentage: 25,
    clientReturnAmount: 40099,
    agencyNetMargin: 104256,
  },
  {
    id: 'pila-005',
    clientId: 'cli-002',
    clientName: 'Manufacturas & Calzado Industrial Colombia S.A.S.',
    month: '2026-07',
    year: 2026,
    ibcReported: 100000000,
    riskClass: 'CLASE_III',
    arlRate: 0.0185,
    arlContribution: 1850000,
    commissionPercentage: 8.5,
    expectedCommission: 157250,
    realPaidCommission: 157250,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'positiva',
    paymentDate: '2026-07-05',
    notes: 'Conciliación OK.',
    retefuenteRate: 0.10,
    retefuenteAmount: 15725,
    netCommissionReceived: 141525,
    clientReturnPercentage: 25,
    clientReturnAmount: 39313,
    agencyNetMargin: 102212,
  },

  // --- MONTAJES PETROLEROS (cli-003) ---
  {
    id: 'pila-006',
    clientId: 'cli-003',
    clientName: 'Metalmecánica & Montajes Petroleros S.A.S.',
    month: '2026-08',
    year: 2026,
    ibcReported: 128000000,
    riskClass: 'CLASE_V',
    arlRate: 0.0548,
    arlContribution: 7014400,
    commissionPercentage: 9.0,
    expectedCommission: 631296,
    realPaidCommission: 631296,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'colpatria',
    paymentDate: '2026-08-10',
    notes: 'Liquidación de comisiones de alto riesgo AXA Colpatria. Retorno 30% reservado para bolsa técnica.',
    retefuenteRate: 0.10,
    retefuenteAmount: 63130,
    netCommissionReceived: 568166,
    clientReturnPercentage: 30,
    clientReturnAmount: 189389,
    agencyNetMargin: 378777,
  },
  {
    id: 'pila-007',
    clientId: 'cli-003',
    clientName: 'Metalmecánica & Montajes Petroleros S.A.S.',
    month: '2026-07',
    year: 2026,
    ibcReported: 125000000,
    riskClass: 'CLASE_V',
    arlRate: 0.0548,
    arlContribution: 6850000,
    commissionPercentage: 9.0,
    expectedCommission: 616500,
    realPaidCommission: 616500,
    difference: 0,
    status: 'CONCILIADO',
    arlId: 'colpatria',
    paymentDate: '2026-07-09',
    notes: 'Conciliación PILA Colpatria conforme.',
    retefuenteRate: 0.10,
    retefuenteAmount: 61650,
    netCommissionReceived: 554850,
    clientReturnPercentage: 30,
    clientReturnAmount: 184950,
    agencyNetMargin: 369900,
  }
];

export const INITIAL_FIELD_VISITS: FieldVisit[] = [
  // VISITA 1: AUDITORÍA 0312 EN CALZADO INDUSTRIAL
  {
    id: 'vis-001',
    clientId: 'cli-002',
    clientName: 'Manufacturas & Calzado Industrial Colombia S.A.S.',
    engineerId: 'user-admin',
    engineerName: 'Ing. Félix Bedoya (Lic. SST 14920)',
    visitDate: '2026-08-12',
    hoursSpent: 8,
    visitType: 'AUDITORIA_0312',
    checklistScore: 86.5,
    standardsCount: 60,
    findings: 'Evaluación de 60 estándares mínimos SG-SST según Resolución 0312 de 2019. Se constata conformación activa de COPASST, matriz de riesgos actualizada y brigada capacitada. Pendiente plan de mantenimiento preventivo de compresores y mediciones higiénicas de ruido.',
    actionPlan: '1. Radicar cronograma de mediciones higiénicas antes del 30 de septiembre. 2. Implementar fichas técnicas de seguridad en solventes y pegantes.',
    observations: 'Auditoría presencial con participación del Gerente General y Responsable SST.',
    status: 'REALIZADA',
    location: 'Planta Chimitá, Bucaramanga',
    hasCost: false,
    visitCost: 0,
    costNotes: 'Cubierto 100% por bolsa de retorno técnico ARL Positiva',
  },

  // VISITA 2: ERGONOMÍA EN PUESTOS DE CORTE
  {
    id: 'vis-002',
    clientId: 'cli-002',
    clientName: 'Manufacturas & Calzado Industrial Colombia S.A.S.',
    engineerId: 'user-medico',
    engineerName: 'Dra. Marcela Salazar (Médico Laboral)',
    visitDate: '2026-08-25',
    hoursSpent: 4,
    visitType: 'ERGONOMICA',
    findings: 'Inspección ergonómica y biomecánica en 38 puestos de corte y costura. Se detectan posturas bípedas prolongadas y flexión cervical repetitiva.',
    actionPlan: 'Instalación de tapetes antifatiga en líneas de pegado y descansapies graduables en máquinas planas. Taller de pausas activas programado.',
    observations: 'Se elabora informe técnico entregado a gerencia.',
    status: 'REALIZADA',
    location: 'Línea de Producción Bucaramanga',
    hasCost: false,
    visitCost: 0,
    costNotes: 'Acompañamiento preventivo cubierto por retorno',
  },

  // VISITA 3: INVESTIGACIÓN DE ACCIDENTE DE TRABAJO EN METALMECÁNICA
  {
    id: 'vis-003',
    clientId: 'cli-003',
    clientName: 'Metalmecánica & Montajes Petroleros S.A.S.',
    engineerId: 'user-admin',
    engineerName: 'Ing. Félix Bedoya (Lic. SST 14920)',
    visitDate: '2026-08-16',
    hoursSpent: 6,
    visitType: 'INSPECCION_SEGURIDAD',
    findings: 'Investigación técnica del accidente de trabajo AT-2026-0814-COLP ocurrido al soldador Pedro Pablo Quintero. Causa raíz: Falla de eslinga de amarre durante maniobra de izaje de tubería estructural de 12 pulgadas.',
    actionPlan: '1. Retiro de eslingas desgastadas y certificación de aparejos. 2. Reinducción en maniobras críticas de izaje y uso de vientos guía.',
    observations: 'Informe de investigación firmado por COPASST y remitido a ARL Colpatria dentro de los 15 días hábiles.',
    status: 'REALIZADA',
    location: 'Taller Central El Centro, Barrancabermeja',
    hasCost: false,
    visitCost: 0,
    costNotes: 'Investigación de AT cubierta 100% por PRAXIS',
  },

  // VISITA 4: CAPACITACIÓN EN AGROQUÍMICOS EN PALMAREAL
  {
    id: 'vis-004',
    clientId: 'cli-001',
    clientName: 'Agroindustrial Palmareal del Llano S.A.S.',
    engineerId: 'user-admin',
    engineerName: 'Ing. Félix Bedoya (Lic. SST 14920)',
    visitDate: '2026-07-20',
    hoursSpent: 4,
    visitType: 'CAPACITACION',
    findings: 'Jornada de capacitación teórico-práctica en almacenamiento seguro, etiquetado SGA y uso de EPP para manejo de agroquímicos con 28 trabajadores de campo.',
    actionPlan: 'Instalación de duchas de emergencia adicionales en bodegas y señalización reflectiva.',
    observations: 'Entrega de constancias de asistencia con evaluación de conocimiento superior al 90%.',
    status: 'COMPLETADA',
    location: 'Hacienda El Amparo, Villavicencio',
    hasCost: false,
    visitCost: 0,
    costNotes: 'Capacitación presencial cubierta por ARL SURA / PRAXIS',
  }
];

export const INITIAL_MEDICAL_RECORDS: MedicalRecord[] = [
  // CASO 1: ACCIDENTE DE TRABAJO CON FURAT RADICADO
  {
    id: 'med-001',
    clientId: 'cli-003',
    clientName: 'Metalmecánica & Montajes Petroleros S.A.S.',
    incidentType: 'ACCIDENTE_TRABAJO',
    employeeDocument: '1.098.452.120',
    employeeName: 'Pedro Pablo Quintero Gómez',
    employeeRole: 'Soldador Estructural Especializado',
    diagnosisCie10: 'S93.4',
    diagnosisDescription: 'Esguince y torcedura de los ligamentos del tobillo derecho con trauma contuso por caída de material',
    daysLost: 18,
    furatFurepCode: 'AT-2026-0814-COLP',
    pveProgram: 'OSTEOMUSCULAR',
    medicalNotes: 'Trabajador refiere que durante maniobra de izaje, perfil metálico se balanceó impactando extremidad inferior derecha. Atendido en Clínica Reina Sofía. Inmovilización con bota walker y terapia física. Alta médica programada para reincorporación escalonada.',
    confidentialFlag: false,
    date: '2026-08-14',
    createdByDoctor: 'Dra. Marcela Salazar (Reg. Médico 8841)',
  },

  // CASO 2: ENFERMEDAD LABORAL CALIFICADA CON FUREL Y PVE
  {
    id: 'med-002',
    clientId: 'cli-003',
    clientName: 'Metalmecánica & Montajes Petroleros S.A.S.',
    incidentType: 'ENFERMEDAD_LABORAL',
    employeeDocument: '79.845.612',
    employeeName: 'Jorge Eliécer Morales Peña',
    employeeRole: 'Operario de Esmerilado y Pulido de Soldadura',
    diagnosisCie10: 'G56.0',
    diagnosisDescription: 'Síndrome del túnel carpiano bilateral derivado de vibración mano-brazo repetitiva',
    daysLost: 15,
    furatFurepCode: 'EL-2026-0622-COLP',
    pveProgram: 'OSTEOMUSCULAR',
    medicalNotes: 'Dictamen de calificación en primera oportunidad emitido por ARL Colpatria determinando origen laboral. Se prescribe reubicación laboral temporal sin exposición a herramientas vibratorias ni agarre forzado. Ingresa al Programa de Vigilancia Epidemiológica Osteomuscular.',
    confidentialFlag: false,
    date: '2026-06-22',
    createdByDoctor: 'Dra. Marcela Salazar (Reg. Médico 8841)',
  },

  // CASO 3: AUSENTISMO COMÚN POR ENFERMEDAD GENERAL
  {
    id: 'med-003',
    clientId: 'cli-003',
    clientName: 'Metalmecánica & Montajes Petroleros S.A.S.',
    incidentType: 'AUSENTISMO_COMUN',
    employeeDocument: '52.981.456',
    employeeName: 'Claudia Patricia Benítez Cárdenas',
    employeeRole: 'Analista de Aseguramiento de Calidad',
    diagnosisCie10: 'J20.9',
    diagnosisDescription: 'Bronquitis aguda no especificada con cuadro respiratorio febril',
    daysLost: 4,
    furatFurepCode: 'EPS-SAN-2026-8821',
    pveProgram: 'RESPIRATORIO',
    medicalNotes: 'Incapacidad expedida por EPS Sanitas por 4 días. Manejo farmacológico ambulatorio. Reincorporada a labores de oficina el 01-09-2026 sin secuelas respiratorias.',
    confidentialFlag: false,
    date: '2026-08-28',
    createdByDoctor: 'Dra. Marcela Salazar (Reg. Médico 8841)',
  },

  // CASO 4: INCIDENTE LABORAL (CASI-ACCIDENTE / NEAR-MISS INVESTIGADO SEGÚN RES. 1401/2007)
  {
    id: 'med-004',
    clientId: 'cli-003',
    clientName: 'Metalmecánica & Montajes Petroleros S.A.S.',
    incidentType: 'INCIDENTE_LABORAL',
    employeeDocument: '80.123.987',
    employeeName: 'Carlos Andrés Mendoza Silva',
    employeeRole: 'Operario de Puente Grúa e Izaje',
    diagnosisCie10: 'Z04.3',
    diagnosisDescription: 'Incidente laboral por ruptura de eslinga sintética en izaje de viga estructural de 2 toneladas sin lesiones a personas',
    daysLost: 0,
    furatFurepCode: 'INC-2026-0819-INT',
    pveProgram: 'NINGUNO',
    medicalNotes: 'Reporte e investigación interna de incidente conforme a la Resolución 1401 de 2007. Durante maniobra de posicionamiento, eslinga sufrió cizallamiento con arista viva. Carga descendió súbitamente sobre caballete de soporte sin generar impacto sobre personal de piso. Trabajador evaluado en enfermería sin signos de trauma ni crisis de ansiedad. Se implementa plan de acción: retiro de eslingas desgastadas y uso obligatorio de protectores de arista de poliuretano.',
    confidentialFlag: false,
    date: '2026-08-19',
    createdByDoctor: 'Dra. Marcela Salazar (Reg. Médico 8841)',
  }
];

export const OCCUPATIONAL_EXAM_CATALOG: ExamCatalogItem[] = [
  {
    id: 'EXAM_CLINICO',
    name: 'Examen Médico Ocupacional con Énfasis Osteomuscular',
    shortName: 'Examen Clínico Osteomuscular',
    category: 'MEDICO_GENERAL',
    normativeBase: 'Resolución 2346 de 2007 / Res. 1843 de 1991',
    targetActivities: ['Universal', 'Administrativo', 'Operativo', 'Construcción', 'Manufactura'],
    estimatedCost: 38000,
    description: 'Evaluación física completa realizada por Médico Especialista en SST. Valora antecedentes, anamnesis por sistemas, columna, arcos de movilidad, reflejos y aptitud postural.',
  },
  {
    id: 'VISIOMETRIA',
    name: 'Visiometría / Optometría Ocupacional Funcional',
    shortName: 'Visiometría Ocupacional',
    category: 'VISION',
    normativeBase: 'Resolución 1843 de 1991 / Resolución 4272 de 2021',
    targetActivities: ['Trabajo en Alturas', 'Conducción (PESV)', 'Oficinas / PVD', 'Metalmecánica', 'Soldadura'],
    estimatedCost: 25000,
    description: 'Tamizaje visual que evalúa agudeza visual lejana y cercana, discriminación cromática (test de Ishihara), forias y estereopsis (percepción de profundidad indispensable para alturas).',
  },
  {
    id: 'AUDIOMETRIA',
    name: 'Audiometría Tonal Ocupacional en Cabina Sonoamortiguada',
    shortName: 'Audiometría Tonal',
    category: 'AUDICION',
    normativeBase: 'Resolución 1843 de 1991 / Guía GATISO Hipoacusia',
    targetActivities: ['Ruido Industrial', 'Metalmecánica', 'Carpintería', 'Aviación', 'Minería', 'Manufactura'],
    estimatedCost: 28000,
    description: 'Exploración de umbrales auditivos vía aérea y ósea de 250 Hz a 8000 Hz en cabina con reposo auditivo previo de 12 a 16 horas para prevención de hipoacusia neurosensorial.',
  },
  {
    id: 'ESPIROMETRIA',
    name: 'Espirometría Clínica Ocupacional (Curva Flujo-Volumen)',
    shortName: 'Espirometría Clínica',
    category: 'PULMONAR',
    normativeBase: 'Resolución 1843 de 1991 / Criterios ATS/ERS',
    targetActivities: ['Exposición a Polvos', 'Soldadura', 'Agroquímicos', 'Palma de Aceite', 'Cemento', 'Pinturas'],
    estimatedCost: 45000,
    description: 'Prueba de función pulmonar que mide FVC, FEV1 y relación FEV1/FVC para descartar patrones obstructivos o restrictivos por inhalación de humos metálicos, polvos o vapores.',
  },
  {
    id: 'EKG_ALTURAS',
    name: 'Electrocardiograma (EKG) de 12 Derivaciones con Informe Ocupacional',
    shortName: 'EKG con Informe (Alturas)',
    category: 'CARDIOVASCULAR',
    normativeBase: 'Resolución 4272 de 2021 (Art. 13) / Res. 0491 de 2020',
    targetActivities: ['Trabajo Seguro en Alturas (> 1.50m)', 'Espacios Confinados', 'Brigadistas', 'Conductores'],
    estimatedCost: 52000,
    description: 'Trazado electrocardiográfico de 12 derivaciones interpretado por especialista para descartar arritmias, bloqueos, hipertrofias o riesgo de síncope que impidan labores en suspensión o alturas.',
  },
  {
    id: 'RX_TORAX_OIT',
    name: 'Radiografía de Tórax PA con Lectura OIT (Neumoconiosis)',
    shortName: 'Rx Tórax Lectura OIT',
    category: 'PULMONAR',
    normativeBase: 'Guía OIT / Res. 1843 de 1991 / GATISO Neumoconiosis',
    targetActivities: ['Minería', 'Canteras', 'Fundición', 'Soldadura Pesada', 'Sandblasting', 'Construcción'],
    estimatedCost: 85000,
    description: 'Placa radiográfica de tórax posteroanterior clasificada por lector certificado OIT para detección temprana de silicosis, asbestosis o neumoconiosis de los trabajadores del carbón.',
  },
  {
    id: 'MANIPULACION_ALIMENTOS',
    name: 'Paquete de Laboratorio para Manipulación Higiénica de Alimentos',
    shortName: 'Paquete Manipuladores (Alimentos)',
    category: 'LABORATORIO',
    normativeBase: 'Resolución 2674 de 2013 / Decreto 3075 de 1997',
    targetActivities: ['Casinos de Alimentación', 'Restaurantes', 'Industria de Alimentos', 'Supermercados'],
    estimatedCost: 65000,
    description: 'Batería de análisis microbiológico que incluye KOH de uñas (descarte micótico), Coprológico seriado (parásitos) y Frotis faríngeo/nasal (Staphylococcus aureus / Streptococcus).',
  },
  {
    id: 'PSICOSENSOMETRICO',
    name: 'Evaluación Psicosensométrica Integral para Conductores y Operadores',
    shortName: 'Psicosensométrico (PESV)',
    category: 'ESPECIALIZADO',
    normativeBase: 'Resolución 1565 de 2014 / Ley 2251 de 2022 / Res. 20223040040595',
    targetActivities: ['Conductores de Carga', 'Transporte de Pasajeros', 'Operadores de Maquinaria Pesada', 'Montacarguistas'],
    estimatedCost: 95000,
    description: 'Evaluación computarizada que mide coordinación bimanual motriz, reactimetría simple y frenado, resistencia a la monotonía y agudeza visual nocturna / encandilamiento.',
  },
  {
    id: 'PERFIL_LIPIDICO_GLICEMIA',
    name: 'Laboratorio de Perfil Lipídico Completo & Glicemia en Ayunas',
    shortName: 'Lípidos & Glicemia',
    category: 'LABORATORIO',
    normativeBase: 'Resolución 1843 de 1991 / Res. 4272 de 2021',
    targetActivities: ['Riesgo Cardiovascular', 'Trabajo en Alturas', 'Turnos Nocturnos', 'Brigadistas'],
    estimatedCost: 35000,
    description: 'Cuantificación en suero de Colesterol Total, HDL, LDL, Triglicéridos y Glicemia basal para cálculo del score Framingham y descarte de hipoglicemias sintomáticas.',
  },
  {
    id: 'COLINESTERASA',
    name: 'Determinación de Colinesterasa Sérica y Eritrocitaria',
    shortName: 'Colinesterasa (Plaguicidas)',
    category: 'LABORATORIO',
    normativeBase: 'Resolución 1843 de 1991 / Decreto 1072 de 2015',
    targetActivities: ['Agroindustria', 'Palma de Aceite', 'Floricultura', 'Fumigación', 'Control de Plagas'],
    estimatedCost: 48000,
    description: 'Monitoreo biológico de exposición a plaguicidas organofosforados y carbamatos para prevención de intoxicaciones agudas y crónicas en trabajadores de campo.',
  },
];

export const INITIAL_OCCUPATIONAL_EXAMS: OccupationalExam[] = [
  // 1. METALMECÁNICA: EXAMEN PERIÓDICO ALTURAS (Armador)
  {
    id: 'exam-001',
    clientId: 'cli-003',
    clientName: 'Metalmecánica & Montajes Petroleros S.A.S.',
    employeeDocument: '80.123.987',
    employeeName: 'Luis Alberto Rincón Gómez',
    employeeRole: 'Armador de Estructuras y Tubería',
    workCenter: 'Taller Central de Maestranza, Corte y Soldadura Pesada',
    examType: 'PERIODICO',
    testsIncluded: ['EXAM_CLINICO', 'AUDIOMETRIA', 'VISIOMETRIA', 'EKG_ALTURAS'],
    totalCost: 143000,
    coveredByReinvestment: true,
    aptitudeStatus: 'APTO_CON_RESTRICCIONES',
    restrictions: 'Uso obligatorio y permanente de gafas de seguridad con fórmula óptica. Control trimestral de presión arterial en enfermería de obra.',
    recommendations: 'Uso continuo de protección auditiva de inserción en zonas de pulido. Mantener hidratación adecuada y pausas activas osteomusculares.',
    specializedEmphasis: 'Trabajo Seguro en Alturas (> 1.50m - Res. 4272/2021)',
    doctorName: 'Dra. Marcela Salazar Botero',
    doctorLicense: 'Licencia SST Res. 4192 / Reg. Médico 8841',
    date: '2026-08-05',
    certificateCode: 'CERT-ALT-2026-0805-01',
    expiresAt: '2027-08-05',
    clinicalNotes: 'Evaluación periódica anual conforme a la Resolución 4272 de 2021. EKG de 12 derivaciones sin alteraciones del ritmo. Visiometría con leve astigmatismo miópico corregido con lentes.',
  },
  // 2. CALZADO INDUSTRIAL: EXAMEN DE INGRESO (Operaria Prensas y Costura)
  {
    id: 'exam-002',
    clientId: 'cli-002',
    clientName: 'Manufacturas & Calzado Industrial Colombia S.A.S.',
    employeeDocument: '63.541.209',
    employeeName: 'Yolanda Patricia Rueda Jaimes',
    employeeRole: 'Operaria de Vulcanizado y Costura',
    workCenter: 'Planta Principal de Prensas, Troquelado y Vulcanizado',
    examType: 'INGRESO',
    testsIncluded: ['EXAM_CLINICO', 'VISIOMETRIA', 'AUDIOMETRIA'],
    totalCost: 91000,
    coveredByReinvestment: true,
    aptitudeStatus: 'APTO',
    restrictions: 'Ninguna para las funciones del cargo propuesto.',
    recommendations: 'Realizar pausas activas para extremidades superiores cada 2 horas. Uso de calzado de seguridad con plantilla ergonómica y protector auditivo de copa.',
    specializedEmphasis: 'Manufactura y Movimientos Repetitivos',
    doctorName: 'Dra. Marcela Salazar Botero',
    doctorLicense: 'Licencia SST Res. 4192 / Reg. Médico 8841',
    date: '2026-08-18',
    certificateCode: 'CERT-ING-2026-0818-02',
    expiresAt: '2027-08-18',
    clinicalNotes: 'Examen de ingreso ocupacional satisfactorio. Buen estado articular y visual. Apta sin restricciones para labores de corte y armado.',
  },
  // 3. PALMAREAL: EXAMEN PERIÓDICO AGROINDUSTRIAL (Sanidad Vegetal)
  {
    id: 'exam-003',
    clientId: 'cli-001',
    clientName: 'Agroindustrial Palmareal S.A.S.',
    employeeDocument: '91.240.852',
    employeeName: 'José Fernando Caicedo Benavides',
    employeeRole: 'Operario de Aplicación y Sanidad Vegetal',
    workCenter: 'Planta Extractora de Aceite de Palma y Biomasa',
    examType: 'PERIODICO',
    testsIncluded: ['EXAM_CLINICO', 'ESPIROMETRIA', 'COLINESTERASA'],
    totalCost: 131000,
    coveredByReinvestment: true,
    aptitudeStatus: 'APTO',
    restrictions: 'Mantener estricto protocolo de EPP para aplicación de agroquímicos (traje Tyvek, máscara con filtro para vapores orgánicos y guantes de nitrilo).',
    recommendations: 'Monitoreo biológico semestral de colinesterasa. Ducha inmediata post-aplicación.',
    specializedEmphasis: 'Manejo Seguro de Plaguicidas y Agroquímicos',
    doctorName: 'Dra. Marcela Salazar Botero',
    doctorLicense: 'Licencia SST Res. 4192 / Reg. Médico 8841',
    date: '2026-07-22',
    certificateCode: 'CERT-AGRO-2026-0722-03',
    expiresAt: '2027-07-22',
    clinicalNotes: 'Colinesterasa sérica y eritrocitaria dentro de rangos basales de normalidad. Espirometría con patrón ventilatorio normal sin obstrucción.',
  },
  // 4. TRANSPORTE / PESV: EXAMEN PERIÓDICO PESV (Conductor Camión Grúa)
  {
    id: 'exam-004',
    clientId: 'cli-003',
    clientName: 'Metalmecánica & Montajes Petroleros S.A.S.',
    employeeDocument: '13.840.119',
    employeeName: 'Gustavo Adolfo Henao Cárdenas',
    employeeRole: 'Conductor de Camión Grúa y Volqueta Pesada',
    workCenter: 'Taller Central de Maestranza, Corte y Soldadura Pesada',
    examType: 'PERIODICO',
    testsIncluded: ['EXAM_CLINICO', 'PSICOSENSOMETRICO', 'VISIOMETRIA', 'AUDIOMETRIA'],
    totalCost: 186000,
    coveredByReinvestment: true,
    aptitudeStatus: 'APTO',
    restrictions: 'Ninguna.',
    recommendations: 'Respetar tiempos máximos de conducción continua (máximo 4 horas). Higiene de sueño y pausas de estiramiento lumbar.',
    specializedEmphasis: 'Plan Estratégico de Seguridad Vial (PESV) / Res. 1565',
    doctorName: 'Dra. Marcela Salazar Botero',
    doctorLicense: 'Licencia SST Res. 4192 / Reg. Médico 8841',
    date: '2026-08-29',
    certificateCode: 'CERT-PESV-2026-0829-04',
    expiresAt: '2027-08-29',
    clinicalNotes: 'Prueba psicosensométrica aprobada en coordinación bimanual (94%), reactimetría simple (91%) y visión nocturna sin alteración del encandilamiento.',
  },
];

export const INITIAL_RUI_PROFILE: RUIIntermediaryProfile = {
  registrationNumber: 'RUI-MINTRABAJO-2024-8849',
  agencyName: 'PRAXIS PREVENCIÓN Y SEGUROS AGENCIA DE SEGUROS LTDA.',
  nit: '901.884.200-1',
  legalRepresentative: 'Félix Bedoya',
  technicalDoctorName: 'Dra. Marcela Salazar Botero',
  technicalDoctorLicense: 'Licencia SST Res. 4192 / Reg. Médico 8841',
  technicalEngineerName: 'Ing. Félix Bedoya',
  technicalEngineerLicense: 'Licencia SST Res. 14920 / COPNIA 25202-0941',
  legalAdvisorName: 'Dr. Alejandro Vargas Quintero',
  legalAdvisorCard: 'Tarjeta Profesional C.S.J. 219.840',
  insurancePolicyNumber: 'POL-RC-SEGUROS-994821',
  insurancePolicyCompany: 'Seguros del Estado S.A.',
  policyExpiryDate: '2027-04-30',
  totalCertifiedHours: 420.5,
};

export const INITIAL_WHATSAPP_MESSAGES: WhatsAppMessage[] = [
  {
    id: 'wapp-001',
    recipientPhone: '+573158890022',
    recipientName: 'Carlos Alberto Mendoza',
    companyName: 'Construcciones & Estructuras del Caribe S.A.S.',
    messageType: 'ALERTA_PILA',
    content: 'Estimado Carlos, te confirmamos que la Carta Oficial de Nombramiento para el cambio de intermediario hacia ARL Bolívar ya fue redactada y enviada a tu correo para firma digital.',
    timestamp: '2026-08-25 09:30',
    status: 'LEIDO',
    direction: 'OUTBOUND',
  },
  {
    id: 'wapp-002',
    recipientPhone: '+573164509988',
    recipientName: 'Álvaro José Carvajal',
    companyName: 'Logística & Distribución Andina S.A.S.',
    messageType: 'ALERTA_PILA',
    content: 'Hola Álvaro, te compartimos el diagnóstico preliminar de comisiones y el análisis de la matriz de centros de trabajo multiriesgo con ARL SURA.',
    timestamp: '2026-09-03 14:15',
    status: 'ENTREGADO',
    direction: 'OUTBOUND',
  },
  {
    id: 'wapp-003',
    recipientPhone: '+573114589210',
    recipientName: 'María Fernanda Gómez',
    companyName: 'Agroindustrial Palmareal del Llano S.A.S.',
    messageType: 'ALERTA_PILA',
    content: 'Estimada María Fernanda, tu planilla PILA de Agosto por $2,352,000 en ARL SURA fue conciliada exitosamente. Se generó la cuenta de cobro correspondiente con el retorno pactado.',
    timestamp: '2026-08-08 11:20',
    status: 'LEIDO',
    direction: 'OUTBOUND',
  },
  {
    id: 'wapp-004',
    recipientPhone: '+573145628901',
    recipientName: 'Ing. Hernán Darío Jaramillo',
    companyName: 'Metalmecánica & Montajes Petroleros S.A.S.',
    messageType: 'ALERTA_PILA',
    content: 'Ingeniero Hernán, confirmamos la radicación formal del FURAT AT-2026-0814-COLP de Pedro Quintero ante AXA Colpatria. El informe de investigación quedó cerrado con el COPASST.',
    timestamp: '2026-08-17 16:40',
    status: 'LEIDO',
    direction: 'OUTBOUND',
  },
];

export const INITIAL_AGENCY_PROFILE: AgencyProfile = {
  name: 'PRAXIS PREVENCIÓN Y SEGUROS AGENCIA DE SEGUROS LTDA.',
  shortName: 'PRAXIS',
  suffix: 'LTDA',
  tagline: 'Prevención y Seguros',
  nit: '901.884.200-1',
  ruiNumber: 'RUI-MINTRABAJO-2024-8849',
  logoUrl: '/praxis-logo.png',
  phone: '(+57) 314 884 9200',
  email: 'gerencia@praxisprevencion.com',
  city: 'Bogotá D.C.',
  address: 'Calle 100 # 19-61 Edificio Capital Tower Of. 802',
};

export const INITIAL_USER_PROFILES: UserProfile[] = [
  {
    id: 'user-admin',
    name: 'Félix Bedoya',
    roleTitle: 'Director Técnico SST & Administrador',
    roleType: 'ADMIN',
    licenseSST: 'Licencia SST Res. 14920 / COPNIA 25202',
    email: 'felix.bedoya@praxisprevencion.com',
    phone: '+57 314 884 9200',
    initials: 'FB',
  },
  {
    id: 'user-medico',
    name: 'Dra. Marcela Salazar',
    roleTitle: 'Médico Especialista Laboral',
    roleType: 'MEDICO_LABORAL',
    licenseSST: 'Reg. Médico 8841 / Lic. SST 4192',
    email: 'marcela.salazar@praxisprevencion.com',
    phone: '+57 310 994 1122',
    initials: 'MS',
  },
  {
    id: 'user-financiero',
    name: 'Santiago Arango',
    roleTitle: 'Analista de Comisiones & Cartera PILA',
    roleType: 'ANALISTA_FINANCIERO',
    licenseSST: 'T.P. Contador 198422',
    email: 'comisiones@praxisprevencion.com',
    phone: '+57 300 552 4433',
    initials: 'SA',
  },
  {
    id: 'user-comercial',
    name: 'Carolina Restrepo',
    roleTitle: 'Gerente de Cuentas & Prospección ARL',
    roleType: 'ASESOR_COMERCIAL',
    licenseSST: 'Id Broker ARL 4492',
    email: 'comercial@praxisprevencion.com',
    phone: '+57 315 220 7788',
    initials: 'CR',
  },
];
