export interface StandardItem0312 {
  id: string; // e.g. '1.1.1'
  cycle: 'PLANEAR' | 'HACER' | 'VERIFICAR' | 'ACTUAR';
  category: string; // e.g. '1.1 Recursos Financieros, Técnicos, Humanos'
  numeral: string;
  description: string;
  criterion: string;
  weight60: number; // Percentage weight in 60-item evaluation
  weight21?: number | boolean; // Weight when evaluated in 21-item context
  weight7?: number | boolean; // Weight when evaluated in 7-item context
  appliesTo7: boolean;
  appliesTo21: boolean;
  appliesTo60: boolean;
}

export type StandardComplianceStatus = 'CUMPLE' | 'NO_CUMPLE' | 'NO_APLICA';

export interface StandardEvaluationRecord {
  status: StandardComplianceStatus;
  observation?: string;
}

export const STANDARDS_0312: StandardItem0312[] = [
  // ==================== I. PLANEAR (60%) ====================
  // 1. RECURSOS (10%)
  {
    id: '1.1.1',
    cycle: 'PLANEAR',
    category: '1.1 Recursos humanos, financieros y técnicos',
    numeral: '1.1.1',
    description: 'Responsable del Sistema de Gestión de Seguridad y Salud en el Trabajo SG-SST',
    criterion: 'Asignar una persona que cumpla con el perfil (Licencia en SST y curso virtual de 50 horas vigente).',
    weight60: 0.5,
    weight21: 4.0,
    weight7: 15.0,
    appliesTo7: true,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '1.1.2',
    cycle: 'PLANEAR',
    category: '1.1 Recursos humanos, financieros y técnicos',
    numeral: '1.1.2',
    description: 'Responsabilidades en el Sistema de Gestión de Seguridad y Salud en el Trabajo',
    criterion: 'Asignar y documentar las responsabilidades específicas en SST a todos los niveles de la empresa.',
    weight60: 0.5,
    weight21: 4.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '1.1.3',
    cycle: 'PLANEAR',
    category: '1.1 Recursos humanos, financieros y técnicos',
    numeral: '1.1.3',
    description: 'Asignación de recursos para el Sistema de Gestión de SST',
    criterion: 'Definir y asignar presupuesto, recursos financieros, técnicos y personal para el diseño e implementación del SG-SST.',
    weight60: 0.5,
    weight21: 4.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '1.1.4',
    cycle: 'PLANEAR',
    category: '1.1 Recursos humanos, financieros y técnicos',
    numeral: '1.1.4',
    description: 'Afiliación al Sistema de Seguridad Social Integral',
    criterion: 'Garantizar la afiliación de todos los trabajadores dependientes e independientes a Salud, Pensión y ARL.',
    weight60: 0.5,
    weight21: 4.0,
    weight7: 15.0,
    appliesTo7: true,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '1.1.5',
    cycle: 'PLANEAR',
    category: '1.1 Recursos humanos, financieros y técnicos',
    numeral: '1.1.5',
    description: 'Pago de pensión especial en actividades de alto riesgo',
    criterion: 'Identificar trabajadores en actividades de alto riesgo (Decreto 2090/2003) y cotizar el porcentaje adicional especial.',
    weight60: 0.5,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '1.1.6',
    cycle: 'PLANEAR',
    category: '1.1 Recursos humanos, financieros y técnicos',
    numeral: '1.1.6',
    description: 'Conformación y funcionamiento del COPASST / Vigía en SST',
    criterion: 'Conformar, elegir y documentar las actas mensuales de reunión del COPASST o nombramiento de Vigía SST.',
    weight60: 0.5,
    weight21: 4.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '1.1.7',
    cycle: 'PLANEAR',
    category: '1.1 Recursos humanos, financieros y técnicos',
    numeral: '1.1.7',
    description: 'Capacitación de los integrantes del COPASST / Vigía en SST',
    criterion: 'Capacitar a los miembros del COPASST o Vigía en sus funciones y responsabilidades legales.',
    weight60: 0.5,
    weight21: 4.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '1.1.8',
    cycle: 'PLANEAR',
    category: '1.1 Recursos humanos, financieros y técnicos',
    numeral: '1.1.8',
    description: 'Conformación y funcionamiento del Comité de Convivencia Laboral',
    criterion: 'Conformar el Comité de Convivencia Laboral y evidenciar reuniones trimestrales y trámite de quejas de acoso laboral.',
    weight60: 0.5,
    weight21: 4.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '1.2.1',
    cycle: 'PLANEAR',
    category: '1.2 Capacitación en el SG-SST',
    numeral: '1.2.1',
    description: 'Programa de Capacitación Anual en Promoción y Prevención',
    criterion: 'Elaborar y ejecutar el Programa de Capacitación Anual en SST firmado por el empleador.',
    weight60: 2.0,
    weight21: 6.0,
    weight7: 15.0,
    appliesTo7: true,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '1.2.2',
    cycle: 'PLANEAR',
    category: '1.2 Capacitación en el SG-SST',
    numeral: '1.2.2',
    description: 'Capacitación, Inducción y Reinducción en SST',
    criterion: 'Realizar actividades de inducción y reinducción a todo el personal nuevo, contratistas y temporales.',
    weight60: 2.0,
    weight21: 5.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '1.2.3',
    cycle: 'PLANEAR',
    category: '1.2 Capacitación en el SG-SST',
    numeral: '1.2.3',
    description: 'Responsables del SG-SST con curso virtual de 50 horas',
    criterion: 'Evidenciar que el responsable y delegados cuentan con la certificación del curso de 50 horas / actualización 20 horas.',
    weight60: 2.0,
    weight21: 5.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },

  // 2. GESTIÓN INTEGRAL DEL SG-SST (15%)
  {
    id: '2.1.1',
    cycle: 'PLANEAR',
    category: '2. Gestión Integral del SG-SST',
    numeral: '2.1.1',
    description: 'Política de Seguridad y Salud en el Trabajo',
    criterion: 'Establecer por escrito, firmada, fechada, divulgada al COPASST y revisada anualmente la Política de SST.',
    weight60: 1.0,
    weight21: 5.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '2.2.1',
    cycle: 'PLANEAR',
    category: '2. Gestión Integral del SG-SST',
    numeral: '2.2.1',
    description: 'Objetivos del SG-SST medibles y alineados',
    criterion: 'Definir objetivos de SST claros, cuantificables, medibles y coherentes con la política.',
    weight60: 1.0,
    weight21: 5.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '2.3.1',
    cycle: 'PLANEAR',
    category: '2. Gestión Integral del SG-SST',
    numeral: '2.3.1',
    description: 'Evaluación inicial del Sistema de Gestión (Línea Base)',
    criterion: 'Realizar la autoevaluación anual conforme a los estándares de la Resolución 0312 de 2019.',
    weight60: 1.0,
    weight21: 5.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '2.4.1',
    cycle: 'PLANEAR',
    category: '2. Gestión Integral del SG-SST',
    numeral: '2.4.1',
    description: 'Plan Anual de Trabajo del SG-SST',
    criterion: 'Elaborar, firmar y controlar el Plan de Trabajo Anual con metas, cronograma de actividades y recursos asignados.',
    weight60: 2.0,
    weight21: 5.0,
    weight7: 15.0,
    appliesTo7: true,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '2.5.1',
    cycle: 'PLANEAR',
    category: '2. Gestión Integral del SG-SST',
    numeral: '2.5.1',
    description: 'Archivo y retención documental del SG-SST',
    criterion: 'Conservar los registros y documentos del SG-SST de manera legible y protegida durante mínimo 20 años.',
    weight60: 2.0,
    weight21: 5.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '2.6.1',
    cycle: 'PLANEAR',
    category: '2. Gestión Integral del SG-SST',
    numeral: '2.6.1',
    description: 'Rendición de cuentas sobre el desempeño del SG-SST',
    criterion: 'Rendir cuentas anualmente al interior de la empresa sobre el desempeño de la seguridad y salud laboral.',
    weight60: 1.0,
    weight21: 5.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '2.7.1',
    cycle: 'PLANEAR',
    category: '2. Gestión Integral del SG-SST',
    numeral: '2.7.1',
    description: 'Matriz Legal en Seguridad y Salud en el Trabajo',
    criterion: 'Disponer de la matriz de requisitos legales aplicables actualizada y con evidencias de cumplimiento.',
    weight60: 2.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '2.8.1',
    cycle: 'PLANEAR',
    category: '2. Gestión Integral del SG-SST',
    numeral: '2.8.1',
    description: 'Mecanismos de comunicación, auto-reporte y consulta en SST',
    criterion: 'Disponer de canales para la recepción y respuesta oportuna de comunicaciones y autorreporte de condiciones de trabajo.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '2.9.1',
    cycle: 'PLANEAR',
    category: '2. Gestión Integral del SG-SST',
    numeral: '2.9.1',
    description: 'Gestión y control de proveedores y contratistas',
    criterion: 'Establecer lineamientos en SST para la selección, evaluación y seguimiento de proveedores y contratistas.',
    weight60: 2.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '2.10.1',
    cycle: 'PLANEAR',
    category: '2. Gestión Integral del SG-SST',
    numeral: '2.10.1',
    description: 'Gestión del cambio en procesos e infraestructura',
    criterion: 'Disponer de un procedimiento para evaluar el impacto sobre SST que puedan generar cambios internos o externos.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '2.11.1',
    cycle: 'PLANEAR',
    category: '2. Gestión Integral del SG-SST',
    numeral: '2.11.1',
    description: 'Adquisiciones y compras en SST',
    criterion: 'Establecer especificaciones técnicas de SST en las compras de productos, insumos, maquinaria y EPP.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },

  // ==================== II. HACER (30%) ====================
  // 3. GESTIÓN DE LA SALUD (20%)
  {
    id: '3.1.1',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.1.1',
    description: 'Evaluaciones Médicas Ocupacionales (Ingreso, Periódicos, Retiro)',
    criterion: 'Realizar exámenes médicos ocupacionales conforme al profesiograma con médico especialista en medicina del trabajo.',
    weight60: 1.0,
    weight21: 5.0,
    weight7: 15.0,
    appliesTo7: true,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '3.1.2',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.1.2',
    description: 'Custodia de Historias Clínicas Ocupacionales',
    criterion: 'Custodia exclusiva por el médico especialista o IPS conforme a la Resolución 2346 de 2007.',
    weight60: 1.0,
    weight21: 4.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '3.1.3',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.1.3',
    description: 'Restricciones y recomendaciones médico-laborales',
    criterion: 'Implementar las recomendaciones y restricciones emitidas por EPS, ARL o médico laboral.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '3.1.4',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.1.4',
    description: 'Perfil sociodemográfico y diagnóstico de condiciones de salud',
    criterion: 'Elaborar el perfil sociodemográfico y el diagnóstico de salud anual de los trabajadores.',
    weight60: 1.0,
    weight21: 4.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '3.1.5',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.1.5',
    description: 'Actividades de medicina del trabajo, promoción y prevención (PVE)',
    criterion: 'Desarrollar programas de vigilancia epidemiológica (biomecánico, psicosocial, auditivo, etc.) según riesgos.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '3.1.6',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.1.6',
    description: 'Información y conceptos de aptitud a los trabajadores',
    criterion: 'Entregar copia a los trabajadores de los conceptos de aptitud laboral emitidos en las evaluaciones médicas.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '3.1.7',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.1.7',
    description: 'Estilos de vida y entornos de trabajo saludables',
    criterion: 'Promover hábitos de vida saludable, pausas activas y campañas de prevención de consumo de tabaco y alcohol.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '3.1.8',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.1.8',
    description: 'Servicios de agua potable, sanitarios y disposición de basuras',
    criterion: 'Suministrar agua potable, servicios sanitarios higiénicos y mecanismos de disposición de basuras.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '3.1.9',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.1.9',
    description: 'Eliminación adecuada de residuos peligrosos y biológicos',
    criterion: 'Eliminar los residuos conforme a la legislación ambiental y normas sanitarias vigentes.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '3.2.1',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.2.1',
    description: 'Reporte de accidentes de trabajo y enfermedades laborales (FURAT / FUREL)',
    criterion: 'Reportar a la ARL y EPS los accidentes de trabajo y enfermedades laborales dentro de los dos (2) días hábiles siguientes.',
    weight60: 2.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '3.2.2',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.2.2',
    description: 'Investigación de accidentes, incidentes y enfermedades laborales',
    criterion: 'Investigar todos los accidentes e incidentes con participación del equipo investigador y COPASST dentro de 15 días.',
    weight60: 2.0,
    weight21: 5.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '3.2.3',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.2.3',
    description: 'Registro y análisis estadístico de accidentes y enfermedades',
    criterion: 'Llevar el registro consolidado y análisis estadístico de la siniestralidad laboral de la empresa.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '3.3.1',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.3.1',
    description: 'Medición de la Severidad de los Accidentes de Trabajo',
    criterion: 'Calcular mensualmente el índice de severidad de los accidentes laborales (días perdidos / cargados).',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '3.3.2',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.3.2',
    description: 'Medición de la Frecuencia de los Accidentes de Trabajo',
    criterion: 'Calcular mensualmente el índice de frecuencia de accidentalidad laboral.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '3.3.3',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.3.3',
    description: 'Medición de la Mortalidad por Accidentes de Trabajo',
    criterion: 'Medir y analizar la tasa de mortalidad derivada de accidentes de trabajo en el año.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '3.3.4',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.3.4',
    description: 'Medición de la Prevalencia de la Enfermedad Laboral',
    criterion: 'Medir el número de casos de enfermedad laboral presentes en la población trabajadora.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '3.3.5',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.3.5',
    description: 'Medición de la Incidencia de la Enfermedad Laboral',
    criterion: 'Medir el número de casos nuevos de enfermedad laboral diagnosticados en el periodo.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '3.3.6',
    cycle: 'HACER',
    category: '3. Gestión de la Salud',
    numeral: '3.3.6',
    description: 'Medición del Ausentismo por causas médicas',
    criterion: 'Llevar el registro y análisis del ausentismo laboral por incapacidades médicas comunes y laborales.',
    weight60: 1.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },

  // 4. GESTIÓN DE PELIGROS Y RIESGOS (15%)
  {
    id: '4.1.1',
    cycle: 'HACER',
    category: '4. Gestión de Peligros y Riesgos',
    numeral: '4.1.1',
    description: 'Metodología para Identificación de Peligros y Valoración de Riesgos (GTC-45)',
    criterion: 'Disponer de metodología documentada (GTC-45 u otra técnica) y actualizarla anualmente o ante eventos.',
    weight60: 4.0,
    weight21: 5.0,
    weight7: 15.0,
    appliesTo7: true,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '4.1.2',
    cycle: 'HACER',
    category: '4. Gestión de Peligros y Riesgos',
    numeral: '4.1.2',
    description: 'Identificación de peligros con participación de los trabajadores',
    criterion: 'Evidenciar la participación de los trabajadores de todos los centros en la identificación de riesgos.',
    weight60: 4.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '4.1.3',
    cycle: 'HACER',
    category: '4. Gestión de Peligros y Riesgos',
    numeral: '4.1.3',
    description: 'Identificación de sustancias catalogadas como carcinógenas o toxicidad aguda',
    criterion: 'Mantener inventario de químicos y sustancias peligrosas con Hojas de Datos de Seguridad (SGA).',
    weight60: 3.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '4.1.4',
    cycle: 'HACER',
    category: '4. Gestión de Peligros y Riesgos',
    numeral: '4.1.4',
    description: 'Mediciones ambientales higiénicas (Ruido, Iluminación, Químicos)',
    criterion: 'Realizar mediciones cuantitativas de factores de riesgo físico, químico y biológico en puestos de trabajo.',
    weight60: 4.0,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '4.2.1',
    cycle: 'HACER',
    category: '4. Gestión de Peligros y Riesgos',
    numeral: '4.2.1',
    description: 'Implementación de medidas de prevención y control de peligros',
    criterion: 'Aplicar la jerarquía de control (Eliminación, sustitución, controles ingeniería, administrativos y EPP).',
    weight60: 2.5,
    weight21: 5.0,
    weight7: 10.0,
    appliesTo7: true,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '4.2.2',
    cycle: 'HACER',
    category: '4. Gestión de Peligros y Riesgos',
    numeral: '4.2.2',
    description: 'Inspecciones periódicas a instalaciones, maquinaria y herramientas',
    criterion: 'Realizar inspecciones de seguridad programadas con el COPASST y listas de chequeo.',
    weight60: 2.5,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '4.2.3',
    cycle: 'HACER',
    category: '4. Gestión de Peligros y Riesgos',
    numeral: '4.2.3',
    description: 'Mantenimiento periódico de instalaciones, equipos y máquinas',
    criterion: 'Ejecutar programa de mantenimiento preventivo y correctivo de instalaciones y maquinaria.',
    weight60: 2.5,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '4.2.4',
    cycle: 'HACER',
    category: '4. Gestión de Peligros y Riesgos',
    numeral: '4.2.4',
    description: 'Entrega, reposición y capacitación en Elementos de Protección Personal (EPP)',
    criterion: 'Suministrar EPP adecuados al riesgo, registrar firmas de entrega y capacitar en uso correcto.',
    weight60: 2.5,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '4.2.5',
    cycle: 'HACER',
    category: '4. Gestión de Peligros y Riesgos',
    numeral: '4.2.5',
    description: 'Procedimientos y permisos de trabajo para tareas de alto riesgo',
    criterion: 'Disponer de permisos de trabajo, listas de chequeo y personal capacitado para alturas, confinados, caliente o energías peligrosas.',
    weight60: 2.5,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '4.2.6',
    cycle: 'HACER',
    category: '4. Gestión de Peligros y Riesgos',
    numeral: '4.2.6',
    description: 'Procedimientos e instructivos internos de seguridad',
    criterion: 'Contar con instructivos y manuales operativos de seguridad para procesos críticos.',
    weight60: 2.5,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },

  // 5. GESTIÓN DE AMENAZAS (10%)
  {
    id: '5.1.1',
    cycle: 'HACER',
    category: '5. Gestión de Amenazas',
    numeral: '5.1.1',
    description: 'Plan de Prevención, Preparación y Respuesta ante Emergencias',
    criterion: 'Elaborar e implementar el plan de emergencias con análisis de vulnerabilidad, simulacros y rutas de evacuación.',
    weight60: 5.0,
    weight21: 5.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },
  {
    id: '5.1.2',
    cycle: 'HACER',
    category: '5. Gestión de Amenazas',
    numeral: '5.1.2',
    description: 'Conformación, capacitación y dotación de la Brigada de Emergencias',
    criterion: 'Conformar la brigada de emergencias con botiquines, extintores y capacitación periódica.',
    weight60: 5.0,
    weight21: 5.0,
    weight7: false,
    appliesTo7: false,
    appliesTo21: true,
    appliesTo60: true,
  },

  // ==================== III. VERIFICAR (5%) ====================
  // 6. VERIFICACIÓN DEL SG-SST (5%)
  {
    id: '6.1.1',
    cycle: 'VERIFICAR',
    category: '6. Verificación del SG-SST',
    numeral: '6.1.1',
    description: 'Indicadores de estructura, proceso y resultado del SG-SST',
    criterion: 'Medir y evaluar semestral y anualmente la ficha técnica de indicadores del SG-SST.',
    weight60: 1.25,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '6.1.2',
    cycle: 'VERIFICAR',
    category: '6. Verificación del SG-SST',
    numeral: '6.1.2',
    description: 'Auditoría anual del SG-SST con participación del COPASST',
    criterion: 'Planear y ejecutar la auditoría anual interna del SG-SST y socializar los resultados.',
    weight60: 1.25,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '6.1.3',
    cycle: 'VERIFICAR',
    category: '6. Verificación del SG-SST',
    numeral: '6.1.3',
    description: 'Revisión por la Alta Dirección anual del SG-SST',
    criterion: 'Realizar la revisión por la alta dirección anual y documentar el acta con directrices y compromisos.',
    weight60: 1.25,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '6.1.4',
    cycle: 'VERIFICAR',
    category: '6. Verificación del SG-SST',
    numeral: '6.1.4',
    description: 'Planificación de la auditoría con el COPASST',
    criterion: 'Involucrar al COPASST en la planeación y cronograma de las auditorías de seguridad.',
    weight60: 1.25,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },

  // ==================== IV. ACTUAR (10%) ====================
  // 7. MEJORAMIENTO (10%)
  {
    id: '7.1.1',
    cycle: 'ACTUAR',
    category: '7. Mejoramiento Continuo',
    numeral: '7.1.1',
    description: 'Acciones preventivas y correctivas con base en resultados del SG-SST',
    criterion: 'Definir e implementar planes de acción para corregir no conformidades detectadas en auditorías e inspecciones.',
    weight60: 2.5,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '7.1.2',
    cycle: 'ACTUAR',
    category: '7. Mejoramiento Continuo',
    numeral: '7.1.2',
    description: 'Acciones de mejora derivadas de investigaciones de accidentes de trabajo',
    criterion: 'Ejecutar las acciones correctivas formuladas en las investigaciones de accidentes y validar su eficacia.',
    weight60: 2.5,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '7.1.3',
    cycle: 'ACTUAR',
    category: '7. Mejoramiento Continuo',
    numeral: '7.1.3',
    description: 'Plan de mejoramiento con base en la evaluación de Estándares Mínimos Res. 0312',
    criterion: 'Formular el plan de mejoramiento derivado de la autoevaluación anual y registrarlo en el aplicativo del MinTrabajo.',
    weight60: 2.5,
    weight21: false,
    weight7: 10.0,
    appliesTo7: true,
    appliesTo21: false,
    appliesTo60: true,
  },
  {
    id: '7.1.4',
    cycle: 'ACTUAR',
    category: '7. Mejoramiento Continuo',
    numeral: '7.1.4',
    description: 'Implementación de medidas y acciones correctivas solicitadas por ARL y MinTrabajo',
    criterion: 'Cumplir los requerimientos y recomendaciones técnicas emitidas por la ARL o el Ministerio del Trabajo.',
    weight60: 2.5,
    weight21: false,
    weight7: false,
    appliesTo7: false,
    appliesTo21: false,
    appliesTo60: true,
  },
];

export function getStandardsByScope(scope: 7 | 21 | 60): StandardItem0312[] {
  if (scope === 7) {
    return STANDARDS_0312.filter((s) => s.appliesTo7);
  }
  if (scope === 21) {
    return STANDARDS_0312.filter((s) => s.appliesTo21);
  }
  return STANDARDS_0312;
}

export function calculateScore0312(
  scope: 7 | 21 | 60,
  evaluations: Record<string, StandardEvaluationRecord>
): {
  score: number;
  maxScore: number;
  rating: 'CRITICO' | 'MODERADAMENTE_ACEPTABLE' | 'ACEPTABLE';
  ratingLabel: string;
  ratingColor: string;
  cumpleCount: number;
  noCumpleCount: number;
  noAplicaCount: number;
} {
  const standards = getStandardsByScope(scope);
  let earned = 0;
  let totalMax = 0;
  let cumple = 0;
  let noCumple = 0;
  let noAplica = 0;

  standards.forEach((s) => {
    let weight = s.weight60;
    if (scope === 21) weight = typeof s.weight21 === 'number' ? s.weight21 : s.weight60;
    if (scope === 7) weight = typeof s.weight7 === 'number' ? s.weight7 : s.weight60;

    totalMax += weight;
    const ev = evaluations[s.id] || { status: 'NO_CUMPLE' };

    if (ev.status === 'CUMPLE') {
      earned += weight;
      cumple++;
    } else if (ev.status === 'NO_APLICA') {
      // Art. 27 Res. 0312: Si no aplica y está justificado legalmente, se le otorga el puntaje total del ítem
      earned += weight;
      noAplica++;
    } else {
      noCumple++;
    }
  });

  const finalScore = totalMax > 0 ? Math.round((earned / totalMax) * 100) : 0;

  let rating: 'CRITICO' | 'MODERADAMENTE_ACEPTABLE' | 'ACEPTABLE' = 'CRITICO';
  let ratingLabel = 'CRÍTICO (< 60%) - Requiere Plan de Mejoramiento Inmediato';
  let ratingColor = 'text-rose-600 bg-rose-50 dark:bg-rose-950/60 border-rose-300 dark:border-rose-800';

  if (finalScore >= 86) {
    rating = 'ACEPTABLE';
    ratingLabel = 'ACEPTABLE (> 85%) - Mantener calificación e incluir en Plan Anual';
    ratingColor = 'text-emerald-600 bg-emerald-50 dark:bg-emerald-950/60 border-emerald-300 dark:border-emerald-800';
  } else if (finalScore >= 60) {
    rating = 'MODERADAMENTE_ACEPTABLE';
    ratingLabel = 'MODERADAMENTE ACEPTABLE (60% - 85%) - Plan de Mejoramiento a 6 meses';
    ratingColor = 'text-amber-600 bg-amber-50 dark:bg-amber-950/60 border-amber-300 dark:border-amber-800';
  }

  return {
    score: finalScore,
    maxScore: 100,
    rating,
    ratingLabel,
    ratingColor,
    cumpleCount: cumple,
    noCumpleCount: noCumple,
    noAplicaCount: noAplica,
  };
}
